table RLS_VendorIdentifierValue
	isHidden
	lineageTag: f3ef12e2-55ac-49a9-b688-929bb335512d

	column FieldValue
		dataType: string
		isHidden
		lineageTag: 7ecc64f2-f59a-4bbe-8e41-bf77b18d5609
		summarizeBy: none
		sourceColumn: FieldValue

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column FilterKind
		dataType: int64
		formatString: 0
		lineageTag: 540df966-abf4-4b96-8b1e-2230a93fae9d
		summarizeBy: sum
		sourceColumn: FilterKind

		annotation SummarizationSetBy = Automatic

	partition RLS_VendorIdentifierValue = m
		mode: import
		queryGroup: RLS
		source =
				let
				    Source = RLS_UserResourceFilters,
				    #"Filtered Rows" = Table.SelectRows(Source, each ([FieldName] = "VendorIdentifier")and ([FilterKind] <> 0)),
				    #"Colonnes supprimées" = Table.RemoveColumns(#"Filtered Rows",{"Email", "FieldName"}),
				    #"Doublons supprimés" = Table.Distinct(#"Colonnes supprimées"),
				    #"Filtered Rows1" = Table.SelectRows(#"Doublons supprimés", each ([FieldValue] <> ""))
				in
				    #"Filtered Rows1"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

