table RLS_PlannerCode
	isHidden
	lineageTag: 7b631059-9de7-41b8-ad9f-e9ea8461c8b9

	column Email
		dataType: string
		isHidden
		lineageTag: da596436-f5f7-475f-a8fc-0938294eca37
		summarizeBy: none
		sourceColumn: Email

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column FieldName
		dataType: string
		isHidden
		lineageTag: e9e22e75-06e4-4cf1-87d1-eba58eab5ebb
		summarizeBy: none
		sourceColumn: FieldName

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column FieldValue
		dataType: string
		isHidden
		lineageTag: 335989c0-780f-4764-a954-33ea28deeb04
		summarizeBy: none
		sourceColumn: FieldValue

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Leng = LEFt(RLS_PlannerCode[Email],27)
		isHidden
		lineageTag: 975a2c83-ddd0-4f62-ae82-c7353dc32e03
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column FilterKind
		dataType: int64
		formatString: 0
		lineageTag: a104190c-bd7a-47ff-ace3-4a1b0ef16528
		summarizeBy: sum
		sourceColumn: FilterKind

		annotation SummarizationSetBy = Automatic

	partition RLS_PlannerCode-47d86f24-5bc3-404a-aec6-f23bb2670fd8 = m
		mode: import
		queryGroup: RLS
		source =
				let
				    Source = #"RLS_UserResourceFilters",
				    #"Filtered Rows" = Table.SelectRows(Source, each ([FieldName] = "PlannerCode")and ([FilterKind] <> 0))
				in
				    #"Filtered Rows"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

