table RLS_Administrator
	isHidden
	lineageTag: ac4ca860-f4cf-4618-b9c5-0f79c3ec0824

	column Email
		dataType: string
		isHidden
		lineageTag: d0476899-7429-4750-b45d-ac10b71d4bd4
		summarizeBy: none
		sourceColumn: Email

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column AD_Key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: bcfb1f7e-2609-4454-b2ac-20346c8eb576
		summarizeBy: none
		sourceColumn: AD_Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition RLS_Administrator-73fa4fc7-41e4-4c3e-a35f-3563c61624a9 = m
		mode: import
		queryGroup: RLS
		source =
				let
				    Source = RLS_Sources,
				    #"AspNetUserRoles développé" = Table.ExpandTableColumn(Source, "AspNetUserRoles", {"UserId", "RoleId", "AspNetRoles", "AspNetUsers"}, {"AspNetUserRoles.UserId", "AspNetUserRoles.RoleId", "AspNetUserRoles.AspNetRoles", "AspNetUserRoles.AspNetUsers"}),
				    #"AspNetUserRoles.AspNetRoles développé" = Table.ExpandRecordColumn(#"AspNetUserRoles développé", "AspNetUserRoles.AspNetRoles", {"Id", "Name", "Description", "PermissionsLastModified", "AspNetRoleClaims", "AspNetUserRoles"}, {"AspNetUserRoles.AspNetRoles.Id", "AspNetUserRoles.AspNetRoles.Name", "AspNetUserRoles.AspNetRoles.Description", "AspNetUserRoles.AspNetRoles.PermissionsLastModified", "AspNetUserRoles.AspNetRoles.AspNetRoleClaims", "AspNetUserRoles.AspNetRoles.AspNetUserRoles"}),
				    #"Lignes filtrées1" = Table.SelectRows(#"AspNetUserRoles.AspNetRoles développé", each ([AspNetUserRoles.AspNetRoles.Name] = "Administrator") and ([Email] <> null)),
				    #"Index ajouté" = Table.AddIndexColumn(#"Lignes filtrées1", "AD_Key", 1, 0, Int64.Type),
				    #"Autres colonnes supprimées" = Table.SelectColumns(#"Index ajouté",{"Email", "AD_Key"})
				in
				    #"Autres colonnes supprimées"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

