table RLS_LocationValue
	isHidden
	lineageTag: a64ed3ff-761b-4303-8f1e-eac62636b20b

	column FieldValue
		dataType: string
		isHidden
		lineageTag: f32795cd-ea25-4ff9-b02b-65162ec9e751
		summarizeBy: none
		sourceColumn: FieldValue

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column FilterKind
		dataType: int64
		formatString: 0
		lineageTag: cb556815-9011-456a-a200-0121cde893f8
		summarizeBy: sum
		sourceColumn: FilterKind

		annotation SummarizationSetBy = Automatic

	partition RLS_LocationValue = m
		mode: import
		queryGroup: RLS
		source =
				let
				    Source = RLS_UserResourceFilters,
				    #"Filtered Rows" = Table.SelectRows(Source, each ([FieldName] = "Location")and ([FilterKind] <> 0)),
				    #"Colonnes supprimées" = Table.RemoveColumns(#"Filtered Rows",{"Email", "FieldName"}),
				    #"Doublons supprimés" = Table.Distinct(#"Colonnes supprimées"),
				    #"Filtered Rows1" = Table.SelectRows(#"Doublons supprimés", each ([FieldValue] <> ""))
				in
				    #"Filtered Rows1"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

