table SupplyOrders
	lineageTag: ef7942ae-bcdb-437a-a974-524186c09f40

	column OrderNumber
		dataType: string
		lineageTag: 67fe600c-6dfe-47c6-9b9f-d007abd32ec2
		summarizeBy: none
		sourceColumn: OrderNumber

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column PartId
		dataType: int64
		formatString: 0
		lineageTag: 1337be11-b06d-4008-94f7-037a8bcc9da1
		summarizeBy: none
		sourceColumn: PartId

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column PartNumber
		dataType: string
		lineageTag: c1b27b07-7d5a-480b-a012-2d5f2f1de08e
		summarizeBy: none
		sourceColumn: PartNumber

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Revision
		dataType: string
		lineageTag: 36ae5dff-89bd-439f-b114-4df57e1db08e
		summarizeBy: none
		sourceColumn: Revision

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Location
		dataType: string
		lineageTag: e6dd6f37-1e4c-4426-aecb-588a2fad7c47
		summarizeBy: none
		sourceColumn: Location

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column OrderDate
		dataType: dateTime
		formatString: Short Date
		lineageTag: d17d7a2f-745a-4de0-8030-9efa746788fa
		summarizeBy: none
		sourceColumn: OrderDate

		variation Variation
			isDefault
			relationship: 8eec4847-cd3e-45b3-bd40-d6f7fffcb82d
			defaultHierarchy: LocalDateTable_747fc653-6dad-4a04-9302-176874489203.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column RequestDate
		dataType: dateTime
		formatString: Short Date
		lineageTag: 8c5a17f7-d053-48ff-a84e-aa69e1cdf1da
		summarizeBy: none
		sourceColumn: RequestDate

		variation Variation
			isDefault
			relationship: 89ec423c-4b22-4814-96de-a8efa71a633a
			defaultHierarchy: LocalDateTable_425e3713-6a45-4fcd-b47c-0d9c861ce46e.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column OriginalRequestDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 44b423aa-4d3f-4bf0-8cfd-1e719c7ea5d0
		summarizeBy: none
		sourceColumn: OriginalRequestDate

		variation Variation
			isDefault
			relationship: c2e74283-137a-411f-92fe-bbfd28360a09
			defaultHierarchy: LocalDateTable_66a3cc7d-ad4d-494d-9251-9260aaa310a2.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column RecommendedRequestDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 24b6ebe3-ff29-48f4-9316-9983338cbeb0
		summarizeBy: none
		sourceColumn: RecommendedRequestDate

		variation Variation
			isDefault
			relationship: 61b0b5f4-9217-4652-b7fc-1bbda66453f0
			defaultHierarchy: LocalDateTable_542428b6-19fc-47eb-9bc2-f2eb4eed446a.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column PromiseDate
		dataType: dateTime
		formatString: Short Date
		lineageTag: ac22f428-8f2f-4035-86ee-8378d402dd43
		summarizeBy: none
		sourceColumn: PromiseDate

		variation Variation
			isDefault
			relationship: 4a728323-32dc-4bda-bd3a-cd61dd3a47d8
			defaultHierarchy: LocalDateTable_1c47ef37-653a-4c3c-b4c8-cd86d491fdfa.'Date Hierarchy'

		changedProperty = FormatString

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column OrderReceiptDate
		dataType: dateTime
		formatString: Short Date
		lineageTag: 30f0d4cc-2ee6-4251-863e-3ee3ca04520e
		summarizeBy: none
		sourceColumn: OrderReceiptDate

		variation Variation
			isDefault
			relationship: 8daf2cad-2f4d-422e-a99a-e1af23491f2a
			defaultHierarchy: LocalDateTable_efdbde67-7275-4f92-9dbe-f534e52facc8.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Quantity
		dataType: double
		lineageTag: b04dca75-9ae4-420a-981f-8a2f6b697e77
		summarizeBy: sum
		sourceColumn: Quantity

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column QuantityTo
		dataType: double
		formatString: #,0
		lineageTag: b4ebbbe6-d049-487a-aa86-00a34e2f0147
		summarizeBy: sum
		sourceColumn: QuantityTo

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column OriginalQuantity
		dataType: double
		lineageTag: 32c9c41b-6e74-4251-b95d-305e63336e9d
		summarizeBy: sum
		sourceColumn: OriginalQuantity

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column RecommendedQuantity
		dataType: double
		lineageTag: 60a5e001-d501-40c0-8f78-4c7444164b05
		summarizeBy: sum
		sourceColumn: RecommendedQuantity

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column OrderType
		dataType: string
		lineageTag: 0c0077a9-a519-4bcf-9507-d907d3121213
		summarizeBy: none
		sourceColumn: OrderType

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 2caf55e8-4808-4264-a6d2-2001cb6442a4
		summarizeBy: none
		sourceColumn: Status

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Value = SupplyOrders[QuantityTo]*RELATED('Parts'[RawMaterialsCost])
		lineageTag: b72f335b-2de0-40e1-a43b-ea6bd7b46887
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Date Tolerance' = ```
			DATEDIFF (SupplyOrders[PromiseDate], TODAY(), DAY ) 
			```
		formatString: 0
		lineageTag: 31bbe22a-c7bd-4a93-9807-9c1e0dae569e
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Vendor
		dataType: string
		lineageTag: 14709204-a1d0-496c-8655-f26a10dc6471
		summarizeBy: none
		sourceColumn: Vendor

		annotation SummarizationSetBy = Automatic

	column LineItem
		dataType: string
		lineageTag: c1277c14-f2ab-4492-9590-0f9c7f943789
		summarizeBy: none
		sourceColumn: LineItem

		annotation SummarizationSetBy = Automatic

	column ActionMessage
		dataType: string
		lineageTag: b350cf0c-6a63-42c3-a160-058e666efd17
		summarizeBy: none
		sourceColumn: ActionMessage

		annotation SummarizationSetBy = Automatic

	column ActionMessageType
		dataType: string
		lineageTag: df136a15-74e4-4983-b793-dcebe96b40f3
		summarizeBy: none
		sourceColumn: ActionMessageType

		annotation SummarizationSetBy = Automatic

	column Id
		dataType: string
		lineageTag: 8eb1556a-ca6e-4454-995b-7e62f43c349b
		summarizeBy: none
		sourceColumn: Id

		annotation SummarizationSetBy = Automatic

	partition SupplyOrders-23e91db8-f24e-405f-963a-a28e21fa43e5 = m
		mode: import
		queryGroup: Source
		source = ```
				let
				    Source = Sql.Database(Server, Database, [Query="SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SupplyOrders' AND TABLE_SCHEMA = 'report'"]),
				    ColumnExists = List.Contains(Source[COLUMN_NAME], "ActionMessageType"),
				    Query = if ColumnExists then
				        "SELECT OrderNumber, Id,Vendor, PartId, PartNumber, Revision, Location, OrderDate, RequestDate, OriginalRequestDate, RecommendedRequestDate, PromiseDate, OrderReceiptDate, Quantity, QuantityTo, OriginalQuantity, LineItem, RecommendedQuantity, OrderType, Status, ActionMessageType FROM report.SupplyOrders WITH (NOLOCK)"
				    else
				        "SELECT OrderNumber, Id,Vendor, PartId, PartNumber, Revision, Location, OrderDate, RequestDate, OriginalRequestDate, RecommendedRequestDate, PromiseDate, OrderReceiptDate, Quantity, QuantityTo, OriginalQuantity, LineItem, RecommendedQuantity, OrderType, Status,'None' ActionMessageType FROM report.SupplyOrders WITH (NOLOCK)",
				    Data = Sql.Database(Server, Database, [Query=Query]),
				    #"Changed Type" = Table.TransformColumnTypes(Data,{{"PromiseDate", type date}}),
				    #"Added Custom" = Table.AddColumn(#"Changed Type", "ActionMessage", each 
				    try 
				        if Record.HasFields(_, "ActionMessageType") then [ActionMessageType] 
				        else "None" 
				    otherwise "None"
				),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Added Custom",{{"Id", type text}})
				in
				    #"Changed Type1"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

