table UDF
	isHidden
	lineageTag: a932af4c-a705-46cd-a10d-5c2c50849703

	column UserDefined1
		dataType: string
		isHidden
		lineageTag: 3cb6997f-b40b-492a-bc9f-17ff5b72f1f9
		summarizeBy: none
		sourceColumn: UserDefined1

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UserDefined2
		dataType: string
		isHidden
		lineageTag: 799ff3e5-3808-4d61-90a9-17922507f529
		summarizeBy: none
		sourceColumn: UserDefined2

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UserDefined3
		dataType: string
		isHidden
		lineageTag: 7f7c6f5f-42a4-4245-9993-a3e31d2aae9a
		summarizeBy: none
		sourceColumn: UserDefined3

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UserDefined4
		dataType: string
		isHidden
		lineageTag: 9e57e0f9-9d81-467f-8965-558355942776
		summarizeBy: none
		sourceColumn: UserDefined4

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UserDefined5
		dataType: string
		isHidden
		lineageTag: 4d4a03a2-828d-4ba6-9f86-4592b41794d5
		summarizeBy: none
		sourceColumn: UserDefined5

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UserDefined6
		dataType: string
		isHidden
		lineageTag: 5ac6464a-26a2-40ac-b767-379df6e6681c
		summarizeBy: none
		sourceColumn: UserDefined6

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UserDefined7
		dataType: string
		isHidden
		lineageTag: 86e14a37-5fc0-4fe4-8205-67f17afc4f7c
		summarizeBy: none
		sourceColumn: UserDefined7

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UserDefined8
		dataType: string
		isHidden
		lineageTag: 5ca4bba7-b656-49ef-92e0-dcc0df9f55f4
		summarizeBy: none
		sourceColumn: UserDefined8

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UserDefined9
		dataType: string
		isHidden
		lineageTag: 6f637827-9435-46bd-bc8b-b0343a5643f6
		summarizeBy: none
		sourceColumn: UserDefined9

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UserDefined10
		dataType: string
		isHidden
		lineageTag: d483da1a-c64c-458e-a532-525ff8b7de43
		summarizeBy: none
		sourceColumn: UserDefined10

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UserDefined11
		dataType: string
		isHidden
		lineageTag: 51cc48c5-8ef8-46dc-87ea-9369f05f6f9d
		summarizeBy: none
		sourceColumn: UserDefined11

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UserDefined12
		dataType: string
		isHidden
		lineageTag: 9ef878d2-d3bd-435f-b9ab-4851c33e4038
		summarizeBy: none
		sourceColumn: UserDefined12

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UserDefined13
		dataType: string
		isHidden
		lineageTag: da883796-34ea-439a-9101-7502c8405a01
		summarizeBy: none
		sourceColumn: UserDefined13

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UserDefined14
		dataType: string
		isHidden
		lineageTag: dc03fa00-f639-4faf-b0ba-77e19cbfff0a
		summarizeBy: none
		sourceColumn: UserDefined14

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UserDefined15
		dataType: string
		isHidden
		lineageTag: 4c247ebd-8e7d-4423-8943-4dca7f619b32
		summarizeBy: none
		sourceColumn: UserDefined15

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UserDefined16
		dataType: string
		isHidden
		lineageTag: 272eb4a6-fcc9-4c8f-8132-a636539cb230
		summarizeBy: none
		sourceColumn: UserDefined16

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition UDF-846fb5be-2999-408b-88e6-7b2aa72c722c = m
		mode: import
		queryGroup: Source
		source =
				let
				    Source = Sql.Database(Server,Database,[Query=" SELECT Value FROM dbo.keyvalueItems where Id='Settings.Global.Engine'"]),
				    #"TransformColumns"=Table.TransformColumns(Source,{{"Value", Json.Document}}),
				    #"Value développé" = Table.ExpandRecordColumn(TransformColumns, "Value", {"UDF1", "UDF2", "UDF3", "UDF4", "UDF5", "UDF6", "UDF7", "UDF8", "UDF9", "UDF10", "UDF11", "UDF12", "UDF13", "UDF14", "UDF15", "UDF16"}, {"UDF1", "UDF2", "UDF3", "UDF4", "UDF5", "UDF6", "UDF7", "UDF8", "UDF9", "UDF10", "UDF11", "UDF12", "UDF13", "UDF14", "UDF15", "UDF16"}),
				    #"Colonnes renommées1" = Table.RenameColumns(#"Value développé",{{"UDF1", "UserDefined1"}, {"UDF2", "UserDefined2"}, {"UDF3", "UserDefined3"}, {"UDF4", "UserDefined4"}, {"UDF5", "UserDefined5"}, {"UDF6", "UserDefined6"}, {"UDF7", "UserDefined7"}, {"UDF8", "UserDefined8"}, {"UDF9", "UserDefined9"}, {"UDF10", "UserDefined10"}, {"UDF11", "UserDefined11"}, {"UDF12", "UserDefined12"}, {"UDF13", "UserDefined13"}, {"UDF14", "UserDefined14"}, {"UDF15", "UserDefined15"}, {"UDF16", "UserDefined16"}}),
				    #"Type modifié" = Table.TransformColumnTypes(#"Colonnes renommées1",{{"UserDefined2", type text}, {"UserDefined1", type text}, {"UserDefined3", type text}, {"UserDefined4", type text}, {"UserDefined5", type text}, {"UserDefined6", type text}, {"UserDefined7", type text}, {"UserDefined8", type text}, {"UserDefined9", type text}, {"UserDefined10", type text}, {"UserDefined11", type text}, {"UserDefined12", type text}, {"UserDefined13", type text}, {"UserDefined14", type text}, {"UserDefined15", type text}, {"UserDefined16", type text}})
				in
				    #"Type modifié"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

