table BOM_Multilevel
	lineageTag: f64e3526-be31-4b3f-8c0f-f94b0601b20e

	measure 'Nb Of Item Children' =
			VAR Measures=DISTINCTCOUNT(BOM_Multilevel[ChildPartId])
			return IF(Measures<>0,Measures,BLANK())
		formatString: #,0
		lineageTag: e9c32073-1430-4a46-9d1e-8cf79dfb66eb

	measure BOMVariant = IF([Nb Of Item Children]<>BLANK(),"1",BLANK())
		lineageTag: 219b6ddb-fd06-424c-8cb7-95da10800b75

	column ChildPartId
		dataType: int64
		formatString: 0
		lineageTag: 091b2f26-7576-4729-b492-92ff4ef05717
		summarizeBy: none
		sourceColumn: ChildPartId

		annotation SummarizationSetBy = Automatic

	column ParentPartId
		dataType: int64
		formatString: 0
		lineageTag: 31bf9e3f-35a7-4990-b85a-82118581c36d
		summarizeBy: none
		sourceColumn: ParentPartId

		annotation SummarizationSetBy = Automatic

	column level
		dataType: int64
		formatString: 0
		lineageTag: 79b75ee3-abf6-4ba7-ac36-386f263b4012
		summarizeBy: sum
		sourceColumn: level

		annotation SummarizationSetBy = Automatic

	column PrevParentId
		dataType: double
		lineageTag: 9753ab6a-47ed-44f7-87ea-9aa9f976e135
		summarizeBy: none
		sourceColumn: PrevParentId

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Ratio
		dataType: double
		lineageTag: 01b61679-ef5d-463e-bf18-5a5171958159
		summarizeBy: sum
		sourceColumn: Ratio

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TopParent = related(Parts[Part_Numb_Location])
		lineageTag: 89a17f4b-5e4f-4a7e-b2b2-4c30992cf89e
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Alert Severity BOMPARENT' = RELATED(BOM_PrevParent[AlertSeverity])
		lineageTag: 0627faed-a651-42c9-a235-eef689094cef
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Child = related(BOM_Child[Part_Numb_Location])
		lineageTag: 6baffba3-7aa8-440c-b2c8-a536bfb484c8
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column PrevParent = related(BOM_PrevParent[Part_Numb_Location])
		lineageTag: 0906d8ac-c7c0-40c7-a3a1-42f5cefc5890
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column PrevPrio = related(BOM_PrevParent[Priority])
		lineageTag: b42669e5-59a9-4782-a309-9503251a0060
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column PrevURL = related(BOM_PrevParent[Url_Workbench])
		lineageTag: ffc0510c-453f-4d80-97a5-485dfc6e3734
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column PrevDLT = related(BOM_PrevParent[RPlusLeadTime])
		formatString: 0
		lineageTag: 4fc30aed-e7ee-4f5f-a669-6acc4ed381d1
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Child InventoryMethod' = related(BOM_Child[InventoryMethod])
		formatString: 0
		lineageTag: 4e95a5bc-6384-48e8-9843-360bfeaa32ac
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Child_Description = related(BOM_PrevParent[Description])
		lineageTag: 41f9d6ab-2228-4bc5-8ae9-849754cd0178
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column PrevParentLocation = related(BOM_PrevParent[Location])
		lineageTag: 0a26507a-0c35-4722-bd65-4eab49264ea6
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column ChildLocation = related(BOM_Child[Location])
		lineageTag: 7ae7a51a-f411-4abb-9b92-72de8c40bd7b
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition BOM_Multilevel = m
		mode: import
		queryGroup: BOM
		source =
				let
				    Source = BOM_Source,
				    #"Requêtes fusionnées" = Table.NestedJoin(Source, {"ChildPartId"}, #"Has Child", {"Id"}, "Has Child", JoinKind.Inner),
				    #"Has Child développé" = Table.ExpandTableColumn(#"Requêtes fusionnées", "Has Child", {"Id"}, {"Has Child.Id"}),
				    #"Colonnes supprimées" = Table.RemoveColumns(#"Has Child développé",{"PrevParentId", "Has Child.Id", "Ratio"}),
				    #"Personnalisée ajoutée" = Table.AddColumn(#"Colonnes supprimées", "PrevParentId", each [ChildPartId]),
				    #"Type modifié" = Table.TransformColumnTypes(#"Personnalisée ajoutée",{{"PrevParentId", Int64.Type}}),
				    #"Personnalisée ajoutée1" = Table.AddColumn(#"Type modifié", "Ratio", each 1),
				    #"Type modifié1" = Table.TransformColumnTypes(#"Personnalisée ajoutée1",{{"Ratio", type number}}),
				    Combine=Table.Combine({#"Type modifié1", Source}),
				    #"Removed Duplicates" = Table.Distinct(Combine)
				in
				    #"Removed Duplicates"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

