table DemandForecasts
	lineageTag: 432ed205-8904-4eda-a83f-c6619e0f240d

	column PartId
		dataType: int64
		formatString: 0
		lineageTag: e37e4fd5-f4bb-4e18-b07b-ba2aabbdfe12
		summarizeBy: none
		sourceColumn: PartId

		annotation SummarizationSetBy = Automatic

	column Value
		dataType: int64
		formatString: 0
		lineageTag: 21d98331-1f57-41d4-beb2-f3ac598b283e
		summarizeBy: sum
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	column WeekOfYear
		dataType: int64
		formatString: 0
		lineageTag: a3516bc6-4804-433e-88df-36f5208419a7
		summarizeBy: sum
		sourceColumn: WeekOfYear

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 4753562c-a0c0-40c0-ab0c-a98b97b108e4
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column ForecastName
		dataType: string
		lineageTag: aae1edeb-3296-4752-a69a-a661eed8c691
		summarizeBy: none
		sourceColumn: ForecastName

		annotation SummarizationSetBy = Automatic

	column 'Start Of Week'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 1c0ede71-ae2e-4633-899c-9f55a5729c09
		summarizeBy: none
		sourceColumn: Start Of Week

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition DemandForecasts = m
		mode: import
		queryGroup: Source
		source = ```
				let
				    Source = Sql.Database(Server, Database, [Query="DECLARE @sqlQuery NVARCHAR(MAX);#(lf)#(lf)IF EXISTS (#(lf)    SELECT 1#(lf)    FROM INFORMATION_SCHEMA.COLUMNS#(lf)    WHERE TABLE_NAME = 'DemandForecasts'#(lf)      AND COLUMN_NAME = 'ForecastName'#(lf))#(lf)BEGIN#(lf)    SET @sqlQuery = #(lf)        N'SELECT PartId, Value, WeekOfYear,Year,ForecastName #(lf)          FROM dbo.DemandForecasts #(lf)          WHERE ForecastName = ''Default'';';#(lf)END#(lf)ELSE#(lf)BEGIN#(lf)    SET @sqlQuery = #(lf)        N'SELECT PartId,Value, WeekOfYear,Year,''Default'' as ForecastName  #(lf)          FROM dbo.DemandForecasts WITH (NOLOCK);';#(lf)END#(lf)#(lf)EXEC sp_executesql @sqlQuery;#(lf)#(lf)"]),
				    #"Filtered Rows" = Table.SelectRows(Source, each ([Value] <> null)),
				        #"WeekNumber" =Table.AddColumn(#"Filtered Rows","Start Of Week", each Date.StartOfWeek(
				                        #date(Number.From([Year]), 1, 1)
				                            + #duration(7 * (Number.From([WeekOfYear]) - 1), 0, 0, 0),
				                        Day.Monday
				                    )
				                ),
				    #"Changed Type" = Table.TransformColumnTypes(WeekNumber,{{"Start Of Week", type date}}),
				    #"next 12 Months" = Table.SelectRows(
				    #"Changed Type",
				    each [Start Of Week] >= Date.AddMonths(Date.From(DateTime.LocalNow()), -12) and [Start Of Week] >= Date.From(DateTime.LocalNow())
				        
				),
				    #"Changed Type1" = Table.TransformColumnTypes(#"next 12 Months",{{"Value", Int64.Type}})
				in
				    #"Changed Type1"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

