table DemandOrders
	lineageTag: 72b0158b-9697-46a7-8ffa-fb3e2a694d35

	measure 'EDU Value Demand' = SUMX('DemandOrders', RELATED(Parts[EffectiveDailyUsage])*RELATED(Parts[RawMaterialsCost]))
		displayFolder: Current Model
		lineageTag: 36708345-8392-469c-a882-220d98afc38d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column OrderNumber
		dataType: string
		lineageTag: 711acbb9-854c-439a-a327-ba4590cbdc84
		summarizeBy: none
		sourceColumn: OrderNumber

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column OrderType
		dataType: string
		lineageTag: 5e6862e4-7d82-4750-89f2-82618e86422f
		summarizeBy: none
		sourceColumn: OrderType

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column OrderDate
		dataType: dateTime
		formatString: Short Date
		lineageTag: 33b21697-cd48-4707-8130-3a0aeb7f94e4
		summarizeBy: none
		sourceColumn: OrderDate

		variation Variation
			isDefault
			relationship: dfd6449e-c865-43dd-96aa-bf1905eecf57
			defaultHierarchy: LocalDateTable_c324442b-e667-45e6-992e-bdf9ebbc3240.'Date Hierarchy'

		changedProperty = FormatString

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column PartId
		dataType: int64
		formatString: 0
		lineageTag: a3be9f0b-17c9-4361-90d8-bb38d93dad85
		summarizeBy: none
		sourceColumn: PartId

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column PartNumber
		dataType: string
		lineageTag: 80d5c1b3-7b0e-494a-ab0c-11e6187c60d9
		summarizeBy: none
		sourceColumn: PartNumber

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Revision
		dataType: string
		lineageTag: 9c81e056-4d8c-4766-974f-2fa3746f0500
		summarizeBy: none
		sourceColumn: Revision

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Location
		dataType: string
		lineageTag: 2b86538e-9c3a-45da-bc25-c01dee446578
		summarizeBy: none
		sourceColumn: Location

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DueDate
		dataType: dateTime
		formatString: Short Date
		lineageTag: 2d26cc3d-52db-415c-affd-2d22f8090d96
		summarizeBy: none
		sourceColumn: DueDate

		changedProperty = FormatString

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column OriginalDueDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 15797f1c-2a54-43af-827d-56151b5a0de4
		summarizeBy: none
		sourceColumn: OriginalDueDate

		variation Variation
			isDefault
			relationship: 8a61535c-aaa6-4dd7-b9fe-4e5d3bfa4558
			defaultHierarchy: LocalDateTable_b716c72d-a53f-4ffd-9e2a-6de3fe80fe38.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Quantity
		dataType: double
		lineageTag: 0f9c3910-2f7d-4014-a17e-10de6e58ada8
		summarizeBy: sum
		sourceColumn: Quantity

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column OriginalQuantity
		dataType: double
		lineageTag: da4c74be-82e5-4b95-a9af-848ae459434f
		summarizeBy: sum
		sourceColumn: OriginalQuantity

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Customer
		dataType: string
		lineageTag: c10a5d70-e088-4bde-9010-472efb95a5f2
		summarizeBy: none
		sourceColumn: Customer

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CustomerIdentifier
		dataType: string
		lineageTag: 6a7b3244-eb88-4a46-b628-6195d7bfbc4e
		summarizeBy: none
		sourceColumn: CustomerIdentifier

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 3a118a85-4758-4d4d-9556-5ccbfe77f11d
		summarizeBy: none
		sourceColumn: Status

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Value = DemandOrders[Quantity]*related('Parts'[RawMaterialsCost])
		lineageTag: 5ecf41c7-2c18-4574-8122-41274594a096
		summarizeBy: sum

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Date Tolerance' = ```
			DATEDIFF (DemandOrders[DueDate], TODAY(), DAY ) 
			```
		formatString: 0
		lineageTag: f63a6af1-5744-4794-8c88-4db35d4fd930
		summarizeBy: sum

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DueDateVStoday
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 71765f52-584c-4568-9149-43fd2d68dbe2
		summarizeBy: none
		sourceColumn: DueDateVStoday

		annotation SummarizationSetBy = Automatic

	column LineItem
		dataType: string
		lineageTag: b684eca7-eb56-4d38-bba8-b70892b5a053
		summarizeBy: none
		sourceColumn: LineItem

		annotation SummarizationSetBy = Automatic

	column Notes
		dataType: string
		lineageTag: e424fcb8-e1b0-4f86-8ef2-7f4e040755c1
		summarizeBy: none
		sourceColumn: Notes

		annotation SummarizationSetBy = Automatic

	column 'Source.OrderNumber'
		dataType: string
		lineageTag: 62fe17b8-050d-4a0b-95f3-1c719b872019
		summarizeBy: none
		sourceColumn: Source.OrderNumber

		annotation SummarizationSetBy = Automatic

	column BackorderOrderNumber = IF(DemandOrders[OrderType] IN {"WO","TO"},DemandOrders[Source.OrderNumber], DemandOrders[OrderNumber])
		lineageTag: 35221573-9bf8-4d07-9e7e-f58e8b24d6d9
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Database_Name
		dataType: string
		lineageTag: 069a9d81-2dd4-4c6e-9b11-657411e1c54c
		summarizeBy: none
		sourceColumn: Database_Name

		annotation SummarizationSetBy = Automatic

	column URL_Workbench
		dataType: string
		lineageTag: a1def2c5-697b-495b-ac26-055a07619488
		summarizeBy: none
		sourceColumn: URL_Workbench

		annotation SummarizationSetBy = Automatic

	partition DemandOrders-db7d9348-4a80-4f43-a485-adc68d3d4c0d = m
		mode: import
		queryGroup: Source
		source =
				let
				    Source = Sql.Database(Server, Database, [Query="SELECT DB_NAME() as Database_Name,OrderNumber,Notes,LineItem,OrderType, OrderDate, PartId,PartNumber, Revision, Location, DueDate, OriginalDueDate, Quantity, OriginalQuantity, Customer, CustomerIdentifier, Status,Source FROM Report.DemandOrders With (NOLOCK)"]),
				    #"Replaced Value" = Table.ReplaceValue(Source,".App","",Replacer.ReplaceText,{"Database_Name"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Replaced Value",{{"DueDate", type date}}),
				    #"Parsed JSON" = Table.TransformColumns(#"Changed Type",{{"Source", Json.Document}}),
				    #"Expanded Source" = Table.ExpandRecordColumn(#"Parsed JSON", "Source", {"OrderNumber"}, {"Source.OrderNumber"}),
				    #"Replaced Errors" = Table.ReplaceErrorValues(#"Expanded Source", {{"Source.OrderNumber", ""}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Replaced Errors",{{"Source.OrderNumber", type text}}),
				    #"Added Custom" = Table.AddColumn(#"Changed Type1", "DueDateVStoday", each if [DueDate]<>null then [DueDate] < DateTime.Date(DateTime.LocalNow()) else null, type logical),
				    #"Added Custom1" = Table.AddColumn(#"Added Custom", "URL_Workbench", each "https://" & [Database_Name] &".demanddriventech.com/workbench?partnumber=" & [PartNumber] & "&location=" & [Location])
				in
				    #"Added Custom1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

