table HistoricalDemand
	lineageTag: 4934c1c5-d3fa-4161-90d3-41c5fbcb1393

	column PartId
		dataType: int64
		formatString: 0
		lineageTag: 5b1a87ff-c830-4640-950a-ca275df488d4
		summarizeBy: none
		sourceColumn: PartId

		annotation SummarizationSetBy = Automatic

	column OrderDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 6c20787f-caf9-4883-8961-de8c79003409
		summarizeBy: none
		sourceColumn: OrderDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column LastMovement = CALCULATE(MAX(HistoricalDemand[OrderDate]),ALLEXCEPT(HistoricalDemand,HistoricalDemand[PartId]))
		formatString: General Date
		lineageTag: d02d087b-051e-4dd9-9ebb-0b269b3f18af
		summarizeBy: none

		variation Variation
			isDefault
			relationship: 2812996c-4114-42ef-b171-eee4566fba73
			defaultHierarchy: LocalDateTable_ef0d61cc-12d9-4f59-bc60-2b0fc49b71b6.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	partition HistoricalDemand = m
		mode: import
		queryGroup: Source
		source = ```
				let
				    Source = Sql.Database(Server, Database, [Query="IF OBJECT_ID('DemandHistoryEdits', 'U') IS NOT NULL
				BEGIN
				    SELECT 
				        t1.PartId, 
				        t1.OrderDate
				        
				    FROM 
				        report.HistoricalDemand t1
				  where t1.OrderDate>='" & Date.ToText(Date.AddDays(Date.From(DateTime.LocalNow()),-HistoryDays),"yyyy-MM-dd") & "';
				END
				ELSE
				BEGIN
				    SELECT 
				        t1.PartId, 
				        t1.OrderDate
				        
				    FROM 
				        report.HistoricalDemand t1 where t1.OrderDate>='" & Date.ToText(Date.AddDays(Date.From(DateTime.LocalNow()),-HistoryDays),"yyyy-MM-dd") & "';
				END;"
				]),
				    #"Type modifié" = Table.TransformColumnTypes(Source,{{"OrderDate", type date}})
				in
				    #"Type modifié"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

