table Parts
	lineageTag: 34ba17aa-65d0-4f35-9129-2ba0269d456d

	measure 'Excess Supply Qty Meseaures' = SUM(Parts[Excess Supply Qty])
		formatString: #,0
		displayFolder: Excess Supply
		lineageTag: f4629ec7-4759-4197-a2f8-ddfdb2fe4721

	measure ExcessSupply_Value = SUM(Parts[Excess Supply Value])
		formatString: #,0
		displayFolder: Excess Supply
		lineageTag: 58c6ef2c-3778-41bb-a96e-c05e3cae9c57

	measure '% excess supply qty' = DIVIDE(Parts[ExcessSupply_Value], 'All Measures'[Total Supply Value])
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Excess Supply
		lineageTag: 0dd575cf-f382-488c-88db-d8afa662068f

	column Id
		dataType: int64
		formatString: 0
		lineageTag: 3274a6ce-44f3-4403-bd8c-ee00fbb20c55
		summarizeBy: none
		sourceColumn: Id

		changedProperty = SortByColumn

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column PartNumber
		dataType: string
		lineageTag: ecbd7cbb-61dc-45a4-aba8-7d9f9ef4e123
		summarizeBy: none
		sourceColumn: PartNumber

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Location
		dataType: string
		lineageTag: 07a56b93-0f14-4c44-9a95-c09240e73236
		summarizeBy: none
		sourceColumn: Location

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column RawMaterialsCost
		dataType: double
		lineageTag: f74b8bbd-7e70-44b6-9d2f-74892a0ee849
		summarizeBy: sum
		sourceColumn: RawMaterialsCost

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Part_Numb_Location
		dataType: string
		lineageTag: 980eb026-7040-46e5-9136-0e7126b68a24
		summarizeBy: none
		sourceColumn: Part_Numb_Location

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Description
		dataType: string
		lineageTag: c8c2cddd-5ca8-49cc-8d8a-f94ca212b93e
		summarizeBy: none
		sourceColumn: Description

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column PlannerCode
		dataType: string
		lineageTag: 8bd40362-4faa-42c0-9fa3-122b4e7fe7a4
		summarizeBy: none
		sourceColumn: PlannerCode

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Vendor
		dataType: string
		lineageTag: 05594193-be48-48bc-a80c-04271c9bc80f
		summarizeBy: none
		sourceColumn: Vendor

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Notes
		dataType: string
		lineageTag: c71281e1-d972-473e-b168-4dd3e6a7facf
		summarizeBy: none
		sourceColumn: Notes

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DataSetId
		dataType: int64
		formatString: 0
		lineageTag: 7b291bf2-a004-4d18-a189-25fbc5070737
		summarizeBy: count
		sourceColumn: DataSetId

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Revision
		dataType: string
		lineageTag: e14d8cb1-9bc3-407a-a7c4-dde56b0753f4
		summarizeBy: none
		sourceColumn: Revision

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column InventoryPlanning
		dataType: string
		lineageTag: 6cb064ec-2782-4837-9467-50a34bf8446d
		summarizeBy: none
		sourceColumn: InventoryPlanning

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column PartType
		dataType: string
		lineageTag: b57925a1-a97a-465f-bfab-6aa96b5020e7
		summarizeBy: none
		sourceColumn: PartType

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DailyUsageType
		dataType: string
		lineageTag: 73b8a842-59e8-4c9a-ae36-36d40d2f8018
		summarizeBy: none
		sourceColumn: DailyUsageType

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DisableAutoProfile
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: e2decbc3-1716-4b23-a79c-a9e6f5c3bd36
		summarizeBy: none
		sourceColumn: DisableAutoProfile

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column MaterialType
		dataType: string
		lineageTag: d86c2382-91e0-4372-84a4-10eac3c54b37
		summarizeBy: none
		sourceColumn: MaterialType

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column VendorIdentifier
		dataType: string
		lineageTag: be9e9c4f-daf5-4d27-bc26-b6aadd6d0045
		summarizeBy: none
		sourceColumn: VendorIdentifier

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column TopOfGreen
		dataType: double
		lineageTag: d05836fb-33bc-4ccc-85a2-941c5a76114b
		summarizeBy: sum
		sourceColumn: TopOfGreen

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TopOfYellow
		dataType: double
		lineageTag: f7ba6cde-afc8-4d51-b49a-871b959ddd22
		summarizeBy: sum
		sourceColumn: TopOfYellow

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TopOfRed
		dataType: double
		lineageTag: 78b611dc-c61e-4809-8c06-0880979bb33b
		summarizeBy: sum
		sourceColumn: TopOfRed

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SupplyOrderQty
		dataType: double
		lineageTag: 24153ffa-b5e5-43fc-95d3-60b7ededf5cb
		summarizeBy: sum
		sourceColumn: SupplyOrderQty

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column OnHandQty
		dataType: decimal
		formatString: 0.00
		lineageTag: f5991127-b812-4ee3-8c1d-cd0ac3ea71e5
		summarizeBy: sum
		sourceColumn: OnHandQty

		changedProperty = FormatString

		changedProperty = DataType

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ForecastedDailyUsage
		dataType: double
		formatString: #,0.00
		lineageTag: 4de0e633-c049-450c-bcf6-c6e11edcda7c
		summarizeBy: sum
		sourceColumn: ForecastedDailyUsage

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column EffectiveDailyUsage
		dataType: double
		formatString: #,0.00
		lineageTag: 9e85efef-9d97-47ed-a660-31f3c7ba25b2
		summarizeBy: sum
		sourceColumn: EffectiveDailyUsage

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column AverageDailyUsage
		dataType: double
		formatString: #,0.00
		lineageTag: 35973939-1967-4a29-a512-c78d51238fa6
		summarizeBy: sum
		sourceColumn: AverageDailyUsage

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column RPlusLeadTime
		dataType: int64
		formatString: 0
		lineageTag: 6dae7d06-fcb7-4721-b8c1-df20cda5e430
		summarizeBy: sum
		sourceColumn: RPlusLeadTime

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column EffectiveLeadTime
		dataType: int64
		formatString: 0
		lineageTag: 0e450ab6-4bf2-43ef-a274-b70b2defae26
		summarizeBy: sum
		sourceColumn: EffectiveLeadTime

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ReorderQuantityFrom
		dataType: double
		lineageTag: c7369aa1-e4e9-4f63-a617-f7d25b742477
		summarizeBy: sum
		sourceColumn: ReorderQuantityFrom

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column UserDefined1
		dataType: string
		lineageTag: 521acd54-4ee4-4515-aef4-a7bf5a2d2267
		summarizeBy: none
		sourceColumn: UserDefined1

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UserDefined2
		dataType: string
		lineageTag: 244a7135-4a3a-451e-9659-2d37b0fec285
		summarizeBy: none
		sourceColumn: UserDefined2

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UserDefined3
		dataType: string
		lineageTag: e38d61e0-e424-44fd-a141-0e5c3dd3d80f
		summarizeBy: none
		sourceColumn: UserDefined3

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UserDefined4
		dataType: string
		lineageTag: b031848a-cda6-4339-a810-f716ecc6dffe
		summarizeBy: none
		sourceColumn: UserDefined4

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UserDefined5
		dataType: string
		lineageTag: 39d31e81-a054-4cc8-9043-dfb73361d7b2
		summarizeBy: none
		sourceColumn: UserDefined5

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UserDefined6
		dataType: string
		lineageTag: bf9e557b-f1c9-49e7-8486-6c6acf65e44c
		summarizeBy: none
		sourceColumn: UserDefined6

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UserDefined7
		dataType: string
		lineageTag: e2c126e5-ebd2-40cc-8e6f-2fd96a18e144
		summarizeBy: none
		sourceColumn: UserDefined7

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UserDefined8
		dataType: string
		lineageTag: c49539e7-04c6-4753-94e1-56a4c25a8971
		summarizeBy: none
		sourceColumn: UserDefined8

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UserDefined9
		dataType: string
		lineageTag: 97ed040e-3b59-4fb4-b992-521ea0a2b0ca
		summarizeBy: none
		sourceColumn: UserDefined9

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UserDefined10
		dataType: string
		lineageTag: 0d687b84-aa7a-4915-9882-32fa612dd220
		summarizeBy: none
		sourceColumn: UserDefined10

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UserDefined11
		dataType: string
		lineageTag: 0d6f19c8-96c6-478e-b06d-fb6e344cc048
		summarizeBy: none
		sourceColumn: UserDefined11

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UserDefined12
		dataType: string
		lineageTag: fa6a6ce8-1b46-444f-ac6d-38d56e3dc797
		summarizeBy: none
		sourceColumn: UserDefined12

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UserDefined13
		dataType: string
		lineageTag: df4a278e-634d-4282-846a-46abc81e4273
		summarizeBy: none
		sourceColumn: UserDefined13

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UserDefined14
		dataType: string
		lineageTag: ee1f68ad-9b34-458a-9d5f-9bf01c1b5f32
		summarizeBy: none
		sourceColumn: UserDefined14

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UserDefined15
		dataType: string
		lineageTag: 3aa3c1fe-bd33-482b-83a6-804ca81d2969
		summarizeBy: none
		sourceColumn: UserDefined15

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UserDefined16
		dataType: string
		lineageTag: 2b6e9b13-2723-4f81-b994-fd1fc3f16166
		summarizeBy: none
		sourceColumn: UserDefined16

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Inventory Method' = ```
			
			                 IF( 'Parts'[InventoryMethod]=1,"Buffer",'Parts'[InventoryPlanning])
			```
		lineageTag: 310eb657-38b0-42bb-933e-6531b18f20ad
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DLT>ELT = 'Parts'[RPlusLeadTime]>'Parts'[EffectiveLeadTime]
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 23689f40-27db-414b-8f93-c3a7457af38a
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Delta ADU FDU' =
			
			IF(([AverageDailyUsage]+'Parts'[ForecastedDailyUsage])<>0,
			DIVIDE(([ForecastedDailyUsage]-[AverageDailyUsage]), ([AverageDailyUsage]+'Parts'[ForecastedDailyUsage]))
			,BLANK())
		formatString: 0\ %;-0\ %;0\ %
		lineageTag: aa23c785-cc52-4363-a375-1767e4075bc2
		summarizeBy: sum

		changedProperty = FormatString

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation __PBI_SemanticLinks = [{"LinkTarget":{"TableName":"Parts","TableItemName":"Delta ADU FDU (bins)","ObjectType":4},"LinkType":"UsedInGroup"}]

	column '% On Hand' = IF('Parts'[OnHandQty]<>0,'Parts'[OnHandQtyMinusDemandAllocationQty]/'Parts'[OnHandQty],0)
		formatString: 0\ %;-0\ %;0\ %
		lineageTag: ed69a4ee-59a2-4de1-be6d-9be7b0d2b673
		summarizeBy: sum

		changedProperty = FormatString

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Max % On Hand' = MAX('Parts'[% On Hand])
		formatString: 0\ %;-0\ %;0\ %
		lineageTag: aca34c05-28cc-4513-a783-cf6a0715cc5a
		summarizeBy: sum

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Min % On Hand' = MIN('Parts'[% On Hand])
		formatString: 0\ %;-0\ %;0\ %
		lineageTag: 68fa0c5f-4c39-449e-9bc9-f1463e4a8b8f
		summarizeBy: sum

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Database_Name
		dataType: string
		lineageTag: 20db9fb2-b804-4926-931d-db6f95a2e9cc
		summarizeBy: none
		sourceColumn: Database_Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Url_Workbench
		dataType: string
		lineageTag: b6421840-9e2c-415c-80bd-35ad0af97577
		summarizeBy: none
		sourceColumn: Url_Workbench

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Lead Time Range' = ceiling('Parts'[RPlusLeadTime],max('Parts'[RPlusLeadTime])/50)
		formatString: 0
		lineageTag: 8097668d-7a70-484e-b619-469585d98831
		summarizeBy: sum

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column InventoryQty
		dataType: double
		formatString: #,0
		lineageTag: 5e24f201-6b55-4278-bb47-4b9c91762507
		summarizeBy: sum
		sourceColumn: InventoryQty

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ReorderQuantityTo
		dataType: double
		lineageTag: 97311365-50ac-426c-ade6-93ef4900f3b2
		summarizeBy: sum
		sourceColumn: ReorderQuantityTo

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NetFlowPercentage
		dataType: double
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: bc9aa06c-a277-4b00-a414-7382edf04dfc
		summarizeBy: sum
		sourceColumn: NetFlowPercentage

		changedProperty = FormatString

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column NetFlowQty
		dataType: double
		lineageTag: 9a14ab01-4f16-41d5-87c5-983082d43c83
		summarizeBy: sum
		sourceColumn: NetFlowQty

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column AlertType
		dataType: string
		lineageTag: df9ccc6c-cb47-48e3-a7e1-d4aef2795beb
		summarizeBy: none
		sourceColumn: AlertType

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SupplyOrderFollowUpBy
		dataType: dateTime
		formatString: General Date
		lineageTag: 129561e1-163d-4765-819b-2871c4a84c00
		summarizeBy: none
		sourceColumn: SupplyOrderFollowUpBy

		variation Variation
			isDefault
			relationship: 1f291248-dc12-4663-8eea-2f0b613658d9
			defaultHierarchy: LocalDateTable_0640d546-9640-4134-abfc-972b8195932a.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column AlertDate
		dataType: dateTime
		formatString: Short Date
		lineageTag: 5ee88c04-2a12-4c6a-9368-b4acb9d9b03d
		summarizeBy: none
		sourceColumn: AlertDate

		variation Variation
			isDefault
			relationship: 537b0c9d-43ad-4867-859a-162ad802db02
			defaultHierarchy: LocalDateTable_ac87a3cb-9e59-4f0b-9c96-fb9a5841d7af.'Date Hierarchy'

		changedProperty = FormatString

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SupplyOrderNote
		dataType: string
		lineageTag: 1b4ac9b3-df6c-4624-bf7e-90a78364064c
		summarizeBy: none
		sourceColumn: SupplyOrderNote

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column AlertSeverity
		dataType: string
		lineageTag: 4a0cd074-c2d2-4060-906b-b3fc52ab5286
		summarizeBy: none
		sourceColumn: AlertSeverity

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Priority
		dataType: string
		lineageTag: 83a6a47c-591c-425f-946c-470972c3e3c4
		summarizeBy: none
		sourceColumn: Priority

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column RequestDate
		dataType: dateTime
		formatString: Short Date
		lineageTag: 0ae66a39-4c16-4f5b-970d-ba1de387912b
		summarizeBy: none
		sourceColumn: RequestDate

		variation Variation
			isDefault
			relationship: e4903312-950a-4801-90c0-fdc49e8f1962
			defaultHierarchy: LocalDateTable_11f45e6c-73cf-44b0-b806-0ca94e47ba8b.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column FixedLeadTime
		dataType: int64
		formatString: 0
		lineageTag: ca5973e7-436f-4a75-93f0-2de1211ab029
		summarizeBy: sum
		sourceColumn: FixedLeadTime

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column GoodsReceiptTime
		dataType: int64
		formatString: 0
		lineageTag: 3a6487c1-294e-4b95-92e0-6588fc15633f
		summarizeBy: sum
		sourceColumn: GoodsReceiptTime

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column AD_Key
		dataType: int64
		formatString: 0
		lineageTag: bf91da63-2578-467f-81b7-1a63f23fc785
		summarizeBy: none
		sourceColumn: AD_Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Excess Supply Value' = IF([Excess Supply Qty]<>BLANK(),[Excess Supply Qty]*'Parts'[RawMaterialsCost],BLANK())
		formatString: #,0
		lineageTag: 73c081e4-eb45-4e84-9683-3ba26b4c8608
		summarizeBy: sum

		changedProperty = FormatString

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column DecoupledLeadTime
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: b88a0d66-a4a7-4e14-b529-8f68aaed7a2f
		summarizeBy: none
		sourceColumn: DecoupledLeadTime

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column OrderMinimumQty
		dataType: double
		formatString: 0
		lineageTag: 276a8c37-8637-4b96-8c88-4c248844382d
		summarizeBy: sum
		sourceColumn: OrderMinimumQty

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column 'Orders Nomber recommended' = DIVIDE('Parts'[TopOfYellow]-'Parts'[TopOfRed],'Parts'[TopOfGreen]-'Parts'[TopOfYellow],BLANK())
		formatString: 0
		lineageTag: 88645f49-3b0f-4227-926a-d0bbd8092fd8
		summarizeBy: sum

		changedProperty = FormatString

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column BoMType
		dataType: string
		lineageTag: a9072215-a7dd-4cf3-be8e-fafe279d0d0e
		summarizeBy: none
		sourceColumn: BoMType

		annotation SummarizationSetBy = Automatic

	column SuspressionIsTrue
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 426b2256-3121-4b55-986b-5fbda18938e3
		summarizeBy: none
		sourceColumn: SuspressionIsTrue

		annotation SummarizationSetBy = Automatic

	column 'Inv Days' = IF('Parts'[EffectiveDailyUsage]<>0,'Parts'[InventoryQty]/'Parts'[EffectiveDailyUsage],BLANK())
		formatString: 0
		lineageTag: f86b15c3-2f8a-41d2-8a17-62e4d3337181
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column 'Inv Target Days' = IF('Parts'[EffectiveDailyUsage]<>0,'Parts'[TargetedInventory]/'Parts'[EffectiveDailyUsage],BLANK())
		formatString: 0
		lineageTag: 66e51896-a0cb-4ae6-bcf5-4c8c61bf1e5a
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column 'Green Zone Days' = DIVIDE('Parts'[TopOfGreen]-'Parts'[TopOfYellow],'Parts'[EffectiveDailyUsage],BLANK() )
		lineageTag: b8ae83f5-591e-4a7d-97cb-c5d3bb7435b3
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Yellow Zones Days' = DIVIDE('Parts'[TopOfYellow]-'Parts'[TopOfRed],'Parts'[EffectiveDailyUsage],BLANK())
		lineageTag: e8282378-a8a6-4073-a5aa-411f93da1d43
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Red Zone Days' = DIVIDE('Parts'[TopOfRed],'Parts'[EffectiveDailyUsage],BLANK() )
		lineageTag: ecda800c-b711-4ef1-a0ba-7eb36939548e
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column OnHandQtyMinusDemandAllocationQty
		dataType: double
		lineageTag: ff317ea0-fabd-4c48-b0ee-e1e73ff71523
		summarizeBy: sum
		sourceColumn: OnHandQtyMinusDemandAllocationQty

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column RZAFName
		dataType: string
		lineageTag: 4f28f4f5-e9fd-4bd0-97f4-bf9fa4b8ebbc
		summarizeBy: none
		sourceColumn: RZAFName

		annotation SummarizationSetBy = Automatic

	column RZAFValue
		dataType: double
		lineageTag: 40574a6c-d91a-45fe-9a04-af2195e018d5
		summarizeBy: sum
		sourceColumn: RZAFValue

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column YZAFName
		dataType: string
		lineageTag: fae4ca2e-9f19-4532-96f5-df073085dcda
		summarizeBy: none
		sourceColumn: YZAFName

		annotation SummarizationSetBy = Automatic

	column YZAFValue
		dataType: double
		lineageTag: 682ed877-667a-4097-a1c1-c1839496b1ef
		summarizeBy: sum
		sourceColumn: YZAFValue

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column InventoryMethod
		dataType: int64
		formatString: 0
		lineageTag: 3a2fe024-f455-4881-a242-30a1bf9e7292
		summarizeBy: sum
		sourceColumn: InventoryMethod

		annotation SummarizationSetBy = Automatic

	column OrderCycle
		dataType: double
		formatString: 0
		lineageTag: 5721355b-2e0a-4c5c-bfd8-5464cadd2f72
		summarizeBy: sum
		sourceColumn: OrderCycle

		annotation SummarizationSetBy = Automatic

	column OrderMaximumQty
		dataType: double
		lineageTag: 56973d27-6079-4a48-970b-d8f28efa850d
		summarizeBy: sum
		sourceColumn: OrderMaximumQty

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column OrderMultipleQty
		dataType: double
		lineageTag: 64e2cff6-4228-4fc1-b9e6-d7a89fb90e11
		summarizeBy: sum
		sourceColumn: OrderMultipleQty

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Excess Supply Qty' =
			VAR Excess='Parts'[NetFlowQty]-'Parts'[TopOfGreen]
			return if (Excess > 'Parts'[SupplyOrderQty],'Parts'[SupplyOrderQty], if (Excess>0,Excess,BLANK()))
		formatString: 0
		lineageTag: 0eb0b9f1-c96e-47a6-8ee4-8fbdab8f30e6
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column ShelfLife
		dataType: int64
		formatString: 0
		lineageTag: 24a84d10-503b-44ad-b3b3-6408f32d13f3
		summarizeBy: sum
		sourceColumn: ShelfLife

		annotation SummarizationSetBy = Automatic

	column SuspressionIsTrueFalse
		dataType: string
		lineageTag: a4df9ab3-60ee-4172-b587-0a168e39f30b
		summarizeBy: none
		sourceColumn: SuspressionIsTrueFalse

		annotation SummarizationSetBy = Automatic

	column TargetedInventory
		dataType: double
		formatString: #,0
		lineageTag: 93cbe25e-e2ff-4242-9550-33e8af388992
		summarizeBy: sum
		sourceColumn: TargetedInventory

		annotation SummarizationSetBy = Automatic

	column ZVR = IF(Parts[RZAFValue]=0 && Parts[YZAFValue]=0,1,0)
		formatString: 0
		lineageTag: 71281827-5c12-483b-aad5-ba599a661ca9
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column TodaysYZAF
		dataType: double
		lineageTag: 41a18364-a785-4332-9e8d-191e59471c53
		summarizeBy: sum
		sourceColumn: TodaysYZAF

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CDAFTargetedInventory
		dataType: double
		lineageTag: 9ae57031-40a1-47bc-b733-e0bf402357fd
		summarizeBy: sum
		sourceColumn: CDAFTargetedInventory

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CDAFTargetedInventoryType
		dataType: string
		lineageTag: 6e977e23-fb89-4a99-b259-394d301dfa25
		summarizeBy: none
		sourceColumn: CDAFTargetedInventoryType

		annotation SummarizationSetBy = Automatic

	column TodaysRZAF
		dataType: double
		lineageTag: db29bbc9-d879-4288-b3b0-2b676d1f60a7
		summarizeBy: sum
		sourceColumn: TodaysRZAF

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column RZAFType
		dataType: string
		lineageTag: 328e6895-8405-4a15-8615-87475ede1456
		summarizeBy: none
		sourceColumn: RZAFType

		annotation SummarizationSetBy = Automatic

	column YZAFType
		dataType: string
		lineageTag: 6777edc0-bfcf-4305-8fe3-b69d5ed101cb
		summarizeBy: none
		sourceColumn: YZAFType

		annotation SummarizationSetBy = Automatic

	column 'Inventory Method_filter' = ```
			
			                 IF( 'Parts'[InventoryMethod]=1,"Buffer","NB")
			```
		lineageTag: 390e387e-4c18-4370-9174-2d8c72610459
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column AlertTypeSeverity
		dataType: string
		lineageTag: 6061f2bc-51f7-4121-adb7-1c4a8f163eb7
		summarizeBy: none
		sourceColumn: AlertTypeSeverity

		annotation SummarizationSetBy = Automatic

	column MaterialAvailabilityShortage
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 63ea2358-aa4a-4d2e-bfe8-b2a2776d4c2d
		summarizeBy: none
		sourceColumn: MaterialAvailabilityShortage

		annotation SummarizationSetBy = Automatic

	column LocationId
		dataType: int64
		formatString: 0
		lineageTag: cf7ac9f8-9188-41a4-ae35-243c0c229ec8
		summarizeBy: none
		sourceColumn: LocationId

		annotation SummarizationSetBy = Automatic

	column Blue
		dataType: string
		lineageTag: c9e0e2ec-f3a7-48ff-88c7-e7ef2b12590e
		summarizeBy: none
		sourceColumn: Blue

		annotation SummarizationSetBy = Automatic

	column Green
		dataType: string
		lineageTag: 205d88ee-e526-46d4-8017-fd9c9ec4216c
		summarizeBy: none
		sourceColumn: Green

		annotation SummarizationSetBy = Automatic

	column Yellow
		dataType: string
		lineageTag: 74d109ca-6d9a-48a2-87b0-3f2528477d56
		summarizeBy: none
		sourceColumn: Yellow

		annotation SummarizationSetBy = Automatic

	column Red
		dataType: string
		lineageTag: 784f6cd7-b33c-407f-8e52-fa61e602993a
		summarizeBy: none
		sourceColumn: Red

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 1017f8a2-2766-4422-a79a-e4c6a36136e3
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column 'Delta ADU FDU ABS' = IF(([AverageDailyUsage]+'Parts'[ForecastedDailyUsage])<>0,ABS(DIVIDE(([ForecastedDailyUsage]-[AverageDailyUsage]),([AverageDailyUsage]+'Parts'[ForecastedDailyUsage]))),BLANK())
		formatString: #,0\ %;-#,0\ %;#,0\ %
		lineageTag: 41399b3b-e0ea-40fb-8f25-da5d5e66b8f0
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Custom
		dataType: string
		lineageTag: 64af0163-ff9b-4bb7-9be6-011bc70eeec1
		dataCategory: WebUrl
		summarizeBy: none
		sourceColumn: Custom

		annotation SummarizationSetBy = Automatic

	column 'ADU VS FDU' = IF(('Parts'[ForecastedDailyUsage]<>0 || 'Parts'[ForecastedDailyUsage]<>BLANK()) && ([AverageDailyUsage]<>0 || [AverageDailyUsage]<>BLANK()),"FDU<>0 and ADU<>0", if(('Parts'[ForecastedDailyUsage]<>0 || 'Parts'[ForecastedDailyUsage]<>BLANK()) && ([AverageDailyUsage]=0 || [AverageDailyUsage]=BLANK()),"FDU<>0 and ADU=0", if(('Parts'[ForecastedDailyUsage]=0 || 'Parts'[ForecastedDailyUsage]=BLANK()) && ([AverageDailyUsage]<>0 || [AverageDailyUsage]<>BLANK()),"FDU=0 and ADU<>0","All")))
		lineageTag: e4725b91-7d88-480f-9533-392a2079aa76
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column DemandAllocationQty
		dataType: double
		lineageTag: 1a6c0abe-07d0-4c73-991c-5b147c00b8be
		summarizeBy: sum
		sourceColumn: DemandAllocationQty

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column RecommendedQtyValue = Parts[ReorderQuantityFrom]*Parts[RawMaterialsCost]
		lineageTag: dd49c728-457b-4658-8f9c-b407829fba65
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DueDate
		dataType: dateTime
		formatString: Short Date
		lineageTag: fd18575e-6a13-42d1-ad33-2016cdb58603
		summarizeBy: none
		sourceColumn: DueDate

		variation Variation
			isDefault
			relationship: 39a62d25-9dce-470c-b6c5-b7649675959e
			defaultHierarchy: LocalDateTable_580e584e-e040-45ff-b90e-e36d46eda993.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Rank = ```
			
			RANKX(
			    ALL(Parts),
			    Parts[RecommendedQtyValue] ,    
			    ,DESC,
			    Dense
			)
			```
		formatString: 0
		lineageTag: a2fd3cf6-bf7d-4d41-9d82-3a4e81217850
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column '% RecoValue' =
			
			DIVIDE(Parts[RecommendedQtyValue], CALCULATE(SUM(Parts[RecommendedQtyValue]), ALLSELECTED(Parts)))
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 9dadd40c-4cfc-4691-9b62-3fb307ec1fdf
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Index = RANKX(ALL('Parts'), 'Parts'[Id], , ASC, Dense)
		formatString: 0
		lineageTag: 6b45ca02-342f-4e4c-bc19-8d6c11af8021
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column URL_AllLocation
		dataType: string
		lineageTag: 148163f5-de01-421b-82cc-0f185e148e51
		summarizeBy: none
		sourceColumn: URL_AllLocation

		annotation SummarizationSetBy = Automatic

	column RZAF_or_YZAF_NotBlank = ```
			
			IF(
			    NOT (
			        ISBLANK(Parts[RZAFName]) && 
			        ISBLANK(Parts[YZAFName])
			    ),
			    1,
			    0
			)
			```
		formatString: 0
		lineageTag: 3828048a-d099-4a2e-a3f0-f0ece256c717
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Delta ADU FDU (bins)' =
			IF(
				ISBLANK('Parts'[Delta ADU FDU]),
				BLANK(),
				IF(
					'Parts'[Delta ADU FDU] >= 0,
					ROUNDDOWN('Parts'[Delta ADU FDU] / 0.65776110945547006, 0) * 0.65776110945547006,
					ROUNDUP('Parts'[Delta ADU FDU] / 0.65776110945547006, 0) * 0.65776110945547006
				)
			)
		formatString: 0\ %;-0\ %;0\ %
		lineageTag: f9392d99-1e68-4df1-9489-23425deae4b6
		summarizeBy: none

		extendedProperty GroupingMetadata =
				{
				  "version": 0,
				  "groupedColumns": [
				    {
				      "Column": {
				        "Expression": {
				          "SourceRef": {
				            "Entity": "Parts"
				          }
				        },
				        "Property": "Delta ADU FDU"
				      }
				    }
				  ],
				  "binningMetadata": {
				    "binSize": {
				      "value": 0.65776110945547006,
				      "unit": 0
				    }
				  }
				}

		annotation GroupingDesignState = {"Version":0,"Sources":[{"Name":"p","Entity":"Parts"}],"GroupedColumns":[{"Column":{"Expression":{"SourceRef":{"Source":"p"}},"Property":"Delta ADU FDU"}}],"BinItem":{"Expression":{"Floor":{"Expression":{"Column":{"Expression":{"SourceRef":{"Source":"p"}},"Property":"Delta ADU FDU"}},"Size":0.65776110945547006}}}}

		annotation SummarizationSetBy = Automatic

	column 'Delta ADU FDU (bins label)' = ```
			
			SWITCH(
			    TRUE(),
			    ISBLANK('Parts'[Delta ADU FDU]), "Blank",
			    'Parts'[Delta ADU FDU] < 0, "Negative (FDU>ADU)",
			    'Parts'[Delta ADU FDU] <= 0.30, "Low (0–30)",
			    'Parts'[Delta ADU FDU] <= 0.50, "High (31–50)",
			    'Parts'[Delta ADU FDU] > 0.50, "Very High (>50)",
			    "Other"
			)
			
			```
		lineageTag: 221b18c0-90b6-4674-9615-0405fc362263
		summarizeBy: none
		sortByColumn: 'Delta ADU FDU (bins sort order)'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Delta ADU FDU (bins sort order)' = ```
			
			SWITCH(
			    TRUE(),
			    ISBLANK('Parts'[Delta ADU FDU]), 7,
			    'Parts'[Delta ADU FDU] > 0.50, 1,         -- Very High
			    'Parts'[Delta ADU FDU] <= 0.50, 2,        -- High
			    'Parts'[Delta ADU FDU] <= 0.30, 3,        -- Moderate
			    'Parts'[Delta ADU FDU] <= 0.20, 4,        -- Low
			    'Parts'[Delta ADU FDU] <= 0.10, 5,        -- Very Low
			    'Parts'[Delta ADU FDU] < 0, 6,
			    8
			)
			
			```
		formatString: 0
		lineageTag: 31acdb9f-0f0a-4905-a2d4-699498a52908
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Target Inventory(RZ+GZ)' =
			
			VAR GreenZone=Parts[TopOfGreen]-Parts[TopOfYellow]
			VAR ExcessBuffer=Parts[TopOfRed]+GreenZone
			RETURN
			ExcessBuffer
		lineageTag: bbc846b5-09f5-407b-b951-6bc1c65e4285
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Total Forecast' = ```
			CALCULATE (
			    SUM ( DemandForecasts[Value] )
			    
			)
			```
		formatString: 0
		lineageTag: a8418b47-9ba8-457c-806a-24b3c6920465
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Excess =
			
			VAR Target= Parts[Target Inventory(RZ+GZ)]
			VAR Excess=Parts[OnHandQty]-Target
			RETURN
			IF(Excess>0,Excess, Blank())
		lineageTag: 172d6e6d-5d90-4cca-be94-526b9a4785f0
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column StockvsDemand =
			
			
			VAR ExcessDemand= Parts[OnHandQty]-Parts[TotalDemandQty]
			return
			IF(ExcessDemand>0,ExcessDemand,BLANK())
		lineageTag: 36a9c320-1f91-447c-9104-c766cb49b8ab
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column TotalDemandQty = ```
			
			CALCULATE (
			    SUM ( DemandOrders[Quantity] )
			    
			)
			```
		lineageTag: bd85e04b-a384-451b-8372-e8c24ad69ede
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ExcessSupplyDemand =
			
			VAR SupplyDemand=Parts[OnHandQty]+ Parts[TotalSupplyQty]-Parts[TotalDemandQty]
			VAR InvSupply=Parts[OnHandQty]+ Parts[TotalSupplyQty]
			RETURN
			IF((InvSupply>Parts[TotalDemandQty]), SupplyDemand,BLANK())
		lineageTag: ea277964-6424-4662-bfc2-29b89e32ccc5
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column TotalSupplyQty = ```
			
			CALCULATE (
			    SUM ( SupplyOrders[Quantity] ),
			     SupplyOrders[Status] = "Committed"
			    
			)
			```
		lineageTag: 2f009b7f-fa18-467a-be8c-f296f5e08c23
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ExcessForecast =
			
			VAR TotalForecast = Parts[Total Forecast]
			VAR SupplyDemand=Parts[OnHandQty]+ Parts[TotalSupplyQty]-TotalForecast
			VAR InvSupply=Parts[OnHandQty]+ Parts[TotalSupplyQty]
			
			RETURN
			IF(
			    NOT ISBLANK(TotalForecast) && InvSupply > TotalForecast,
			    SupplyDemand,
			    BLANK()
			)
		lineageTag: caea8b32-6f21-4d19-89b5-39ee38be346f
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column BlankFlag = ```
			
			IF(
			    NOT(ISBLANK(Parts[RZAFName])) ||
			    NOT(ISBLANK(Parts[YZAFName])),
			    1,
			    0
			)
			
			```
		formatString: 0
		lineageTag: c4d24a36-d03a-4b10-8238-0f62c3aa8376
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition Parts-c69e773b-3d8c-4c2b-8128-ad8416eb28d7 = m
		mode: import
		queryGroup: Source
		source =
				let
				    #"Parts" = Sql.Database(Server, Database, [Query="DECLARE @sqlQuery NVARCHAR(MAX);#(lf)#(lf)IF COL_LENGTH('report.parts', 'RZAFNames') IS NOT NULL#(lf)#(lf)--suppression jointure report.BufferProfiles pour recuperation champs  RedSafetyZone,RedZoneBase,GreenZoneBase demandee par Hutchinson cim le 16-01-25 mais non utilisee#(lf)#(lf)BEGIN#(lf)#(lf)SET @sqlQuery = '#(lf)    SELECT DB_NAME() as Database_Name,p.Id,p.DataSetId, p.PartNumber,p.PartType, p.Revision,p.LocationId, p.Location,p.OrderCycle,p.OrderMaximumQty, p.OrderMultipleQty, p.OrderMinimumQty, p.MaterialAvailabilityShortage,p.VendorIdentifier,p.Description,p.InventoryMethod, p.InventoryPlanning,p.DailyUsageType, p.DisableAutoProfile, p.RawMaterialsCost,p.PlannerCode, p.MaterialType, p.Notes, p.Vendor,p.TopOfGreen,p.TopOfYellow,p.TopOfRed,p.OnHandQty,p.ForecastedDailyUsage, p.NetFlowPercentage,p.NetFlowQty,p.DemandAllocationQty,p.OnHandQtyMinusDemandAllocationQty,p.AlertType,p.FixedLeadTime,p.GoodsReceiptTime, p.SupplyOrderFollowUpBy,p.AlertDate,SupplyOrderNote,p.AlertSeverity,p.EffectiveDailyUsage,p.ReorderQuantityTo, p.BoMType,p.Priority,p.InventoryQty,p.DecoupledLeadTime,p.TargetedInventory,p.AverageDailyUsage, p.RPlusLeadTime, p.RequestDate, p.DueDate,p.EffectiveLeadTime,p.SupplyOrderQty,p.RZAFValue,p.YZAFValue,p.TodaysYZAF,p.CDAFTargetedInventory, p.CDAFTargetedInventoryType, p.TodaysRZAF,p.ShelfLife, p.UserDefined1,p.ReorderQuantityFrom,p.UserDefined2,p.UserDefined3,p.UserDefined4,p.UserDefined5,p.UserDefined6,p.UserDefined7,p.UserDefined8,p.UserDefined9,p.UserDefined10,p.UserDefined11,p.UserDefined12,p.UserDefined13,p.UserDefined14,p.UserDefined15,p.UserDefined16,p.YZAFNames as YZAFName,p.RZAFNames as RZAFName ,p.YZAFTypeDescriptions as YZAFType,p.RZAFTypeDescriptions as RZAFType,case when p.NetFlowQty> p.TopOfGreen and p.TopOfGreen > 0 then ''Blue'' else  null end as ""Blue"", case when p.NetFlowQty > p.TopOfYellow and p.NetFlowQty <=p.TopOfGreen then ''Green'' else  null end  as ""Green"",case when p.NetFlowQty > p.TopOfRed and p.NetFlowQty <= p.TopOfYellow then ''Yellow'' else  null end ""Yellow"", case when p.NetFlowQty<=p.TopOfRed and p.TopOfGreen> 0 then ''Red'' else null end ""Red"" FROM report.Parts p With (NOLOCK)   ' ;#(lf)END#(lf)#(lf)ELSE#(lf)BEGIN#(lf)SET @sqlQuery = '#(lf)    SELECT DB_NAME() as Database_Name,p.Id,p.DataSetId, p.PartNumber,p.PartType, p.Revision,p.LocationId, p.Location,p.OrderCycle,p.OrderMaximumQty, p.OrderMultipleQty, p.OrderMinimumQty, p.MaterialAvailabilityShortage,p.VendorIdentifier,p.Description,p.InventoryMethod, p.InventoryPlanning,p.DailyUsageType, p.DisableAutoProfile, p.RawMaterialsCost,p.PlannerCode, p.MaterialType, p.Notes, p.Vendor,p.TopOfGreen,p.TopOfYellow,p.TopOfRed,p.OnHandQty,p.ForecastedDailyUsage, p.NetFlowPercentage,p.NetFlowQty,p.DemandAllocationQty,p.OnHandQtyMinusDemandAllocationQty,p.AlertType,p.FixedLeadTime,p.GoodsReceiptTime, p.SupplyOrderFollowUpBy,p.AlertDate,SupplyOrderNote,p.AlertSeverity,p.EffectiveDailyUsage,p.ReorderQuantityTo, p.BoMType,p.Priority,p.InventoryQty,p.DecoupledLeadTime,p.TargetedInventory,p.AverageDailyUsage, p.RPlusLeadTime, p.RequestDate, p.DueDate,p.EffectiveLeadTime,p.SupplyOrderQty,p.RZAFName,p.RZAFValue,p.YZAFName,p.YZAFValue,p.TodaysYZAF,p.CDAFTargetedInventory, p.CDAFTargetedInventoryType, p.TodaysRZAF,p.RZAFType,p.YZAFType,p.ShelfLife, p.UserDefined1,p.ReorderQuantityFrom,p.UserDefined2,p.UserDefined3,p.UserDefined4,p.UserDefined5,p.UserDefined6,p.UserDefined7,p.UserDefined8,p.UserDefined9,p.UserDefined10,p.UserDefined11,p.UserDefined12,p.UserDefined13,p.UserDefined14,p.UserDefined15,p.UserDefined16,case when p.NetFlowQty> p.TopOfGreen and p.TopOfGreen > 0 then ''Blue'' else  null end as ""Blue"", case when p.NetFlowQty > p.TopOfYellow and p.NetFlowQty <=p.TopOfGreen then ''Green'' else  null end  as ""Green"",case when p.NetFlowQty > p.TopOfRed and p.NetFlowQty <= p.TopOfYellow then ''Yellow'' else  null end ""Yellow"", case when p.NetFlowQty<=p.TopOfRed and p.TopOfGreen> 0 then ''Red'' else null end ""Red""  FROM report.Parts p With (NOLOCK)';#(lf)END#(lf)EXEC sp_executesql @sqlQuery;"]),
				    #"Added Custom4" = Table.AddColumn(Parts, "Status", each Text.Combine({[Blue], [Green], [Yellow], [Red]}, ""), type text),
				    #"Valeur remplacée5" = Table.ReplaceValue(#"Added Custom4",".App","",Replacer.ReplaceText,{"Database_Name"}),
				    #"Type modifié3" = Table.TransformColumnTypes(#"Valeur remplacée5",{{"InventoryMethod", type text}}),
				    #"Personnalisée ajoutée2" = Table.AddColumn(#"Type modifié3", "Personnalisé", each if [InventoryMethod] = "NB" or [InventoryMethod] = "Non-Buffered" or [InventoryMethod] = "Lead Time Managed" or [InventoryMethod] = "LTM" then 0 else if [InventoryMethod] = "0" then 0 else 1),
				    #"Added Custom5" = Table.AddColumn(#"Personnalisée ajoutée2", "AlertTypeSeverity", each Text.Combine({[AlertType], [AlertSeverity]}, "#(tab)"),type text),
				    #"Colonnes supprimées1" = Table.RemoveColumns(#"Added Custom5",{"InventoryMethod"}),
				    #"Colonnes renommées1" = Table.RenameColumns(#"Colonnes supprimées1",{{"Personnalisé", "InventoryMethod"}}),
				    #"Type modifié2" = Table.TransformColumnTypes(#"Colonnes renommées1",{{"InventoryMethod", Int64.Type}}),
				    #"Added Custom6" = Table.AddColumn(#"Type modifié2", "Custom", each if [InventoryMethod]=1 then "iVBORw0KGgoAAAANSUhEUgAAAEsAAABBCAMAAACuC6m+AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAHUUExURQAAAE1ZTVJSUk5ZTktbSxqmGgDMAA+1D0xaTFBQUDKBMiaRJk9PT0tcS0JqQlNTU05YTgq8CgXEBU1XTV9fXySWJFFRUT5uPk9VTwPJA0xcTBWuFQ25DUxZTC+FL0lfSR+eHxepFztyO09UTymOKSGaIU1aTUdiR05WTgjBCFlcTVJoRl1dS8nJGv//AN7eD1hjSU5UTpmZMLOzJFJdS2hoR3qEOVBVUFZXT/T0BVdaTl5eS1lhSouLN1ZZTl9gTHR+PE1YTVpaTenpCvr6A1BWUFxcS76+H9TUFVthSouMNqSnKVNWT1VVVVtbTXB4QF5eTVdZT1lZTlxeTH1+O52iLFJYTVhYT2ZsRU9XT11dTNnZElZYT1ZWT6WmKltdS3R0QpibL2drRmBgTFdXUFZWTlxZTF1LS8kaGv8AAN4PD11OTYo3NqUqKlVPT1tNTW1FRVxNS9kSEu8ICFhOTb4fH2hIR4Q7OlpPTukKCvoDA1pOTdQVFV1OTH0+PJkxMFdQT2NKSVxOS84XF5E1M7MkJFdPTk1NTWBMTHJEQltOTFRQT6UrKVtOS1RUVIo4NldQUPQFBVdXV1lPTIM9OWxGRFhPTlFVUZgyL19NS1VRUAAAAOL0rPEAAACcdFJOU///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////AL9nXxsAAAAJcEhZcwAAFxEAABcRAcom8z8AAAI9SURBVFhHrZe/S+RAFMctgoULWySllYKlPxD2YIsDQeEWJNhIygOreKLTrXDNWsiSejvh/bM3Sb6TzK/bvJnx4zaz7+XDm+fXVQ8oE0WZ/BJlmZF0HR9+B7mQLjrCKY1ZOxdlOKUxp9bV5DimkJedqzjDOYWTrHPRHOcUjqSndZU4pyDH6lzpqchz5fqGVMwK5UpPxWmr6V2pqcib0ZWaiuN2Xb2LTvFeLG0ilCv1kt1YypWWin5dcDUzvBvHmT5XYiq6RIyulIV1oZfAVQkhmtjXvOolynV+Ec0tVMpF1yhEcG+7FihE8EN+pHYoV3mHSjgVVj+44hc2rGtw0U+UghnWNboqlIK5UVfUXEvUQqk8c/1CLZDVoBpdsQv77XNFLuxhWJfuukU1jBqPSzTXPapBrFToJaOLHlEO4mm8ou6qUQ5iMa5ed1WXqAew1FSG6wkNAZz/x0U3aAhAX5fhqsM/dxYCz7borqsVOtgstUSYLhJNILW+LtNVf/4J40VLveWiV/Rw2errslwCPVze8VyP5XpBE4+dMZbt2qKLx3qfi2p08djgKWC5xA5tLIzvoutao43D534XbdDH4aP9o17DdjXo42CN5bhKfvR3xg+jxHbV/Ohvp+YKSIUZeonjqv6idRL7ip653tA6xbN9RddF7+id4tVKhM/Fjb4zlseVPaN5P+bHYIdnLl703/TfQD2ui2rWJZ1E+F2c6O/6f80MPK7iC/37WLvr8rlY0d84ifC7RFNMfjmhJ6J/M7LunRar+S0AAAAASUVORK5CYII=" else null,type text),
				    #"Added Custom7" = Table.AddColumn(#"Added Custom6", "Part_Numb_Location", each Text.Combine({[PartNumber], "-", [Location],"-",[Revision]}), type text),
				    #"Index ajouté" = Table.AddColumn(#"Added Custom7", "AD_Key", each 1, Int64.Type),
				    #"Personnalisée ajoutée1" = Table.AddColumn(#"Index ajouté", "Url_Workbench", each "https://" & [Database_Name] &".demanddriventech.com/workbench?partnumber=" & [PartNumber] & "&location=" & [Location], type text),
				    #"Added Custom8" = Table.AddColumn(#"Personnalisée ajoutée1", "URL_AllLocation", each "https://" & [Database_Name] &".demanddriventech.com/workbench?partnumber=" & [PartNumber]),
				    #"Requêtes fusionnées" = Table.NestedJoin(#"Added Custom8", {"Id"}, PartTransitions, {"SourcePartId"}, "report_PartTransitions", JoinKind.LeftOuter),
				    #"report_PartTransitions développé" = Table.ExpandTableColumn(#"Requêtes fusionnées", "report_PartTransitions", {"SuspressionIsTrue"}, {"SuspressionIsTrue"}),
				    #"Doublons supprimés" = Table.Distinct(#"report_PartTransitions développé"),
				    #"Valeur remplacée1" = Table.ReplaceValue(#"Doublons supprimés",null,0,Replacer.ReplaceValue,{"OrderMaximumQty"}),
				    #"Valeur remplacée2" = Table.ReplaceValue(#"Valeur remplacée1",null,0,Replacer.ReplaceValue,{"OrderCycle"}),
				    #"Valeur remplacée3" = Table.ReplaceValue(#"Valeur remplacée2",null,0,Replacer.ReplaceValue,{"OrderMultipleQty"}),
				    #"Valeur remplacée4" = Table.ReplaceValue(#"Valeur remplacée3",null,0,Replacer.ReplaceValue,{"OrderMinimumQty"}),
				    #"Personnalisée ajoutée3" = Table.AddColumn(#"Valeur remplacée4", "SuspressionIsTrueFalse", each if [SuspressionIsTrue]=true then "True" else "False", type text),
				    #"Doublons supprimés1" = Table.Distinct(#"Personnalisée ajoutée3", {"Id"})
				in
				    #"Doublons supprimés1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

