table RLS_Location
	isHidden
	lineageTag: 27a0f59d-c0e3-4328-ab06-2e1447cceba5

	column Email
		dataType: string
		isHidden
		lineageTag: 9887510e-7270-4972-843e-bab30713d39a
		summarizeBy: none
		sourceColumn: Email

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column FieldName
		dataType: string
		isHidden
		lineageTag: f30cc08f-c1f5-4332-af49-5de821cc21e4
		summarizeBy: none
		sourceColumn: FieldName

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column FieldValue
		dataType: string
		isHidden
		lineageTag: 04938526-dab9-4e09-ab6a-ccbb65cc4ab7
		summarizeBy: none
		sourceColumn: FieldValue

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Leng = LEFT(RLS_Location[Email],27)
		isHidden
		lineageTag: 085933b5-1639-4aef-b1f7-931e50bfb5c9
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column FilterKind
		dataType: int64
		formatString: 0
		lineageTag: 16ed95a2-3ccd-43c1-b484-3b09e6b25620
		summarizeBy: sum
		sourceColumn: FilterKind

		annotation SummarizationSetBy = Automatic

	partition RLS_Location-09146fcc-dbfb-4227-9359-95781aa5cea3 = m
		mode: import
		queryGroup: RLS
		source =
				let
				    Source = #"RLS_UserResourceFilters",
				    #"Filtered Rows" = Table.SelectRows(Source, each ([FieldName] = "Location") and ([FilterKind] <> 0) )
				in
				    #"Filtered Rows"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

