table AdjustmentFactors
	lineageTag: f4a2ec6d-4695-4d1d-a80e-cd63d3603e59

	measure 'Units Coverage' = ```
			SUM(AdjustmentFactors[Units Coverage Val])   
			```
		formatString: #,0
		lineageTag: 2dc9c264-cec0-4e06-ae38-2d68a3b747ee

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Units Coverage( Qty)' = SUM(AdjustmentFactors[UnitsCoverage])
		formatString: #,0
		lineageTag: fa5a1ac4-ec74-42a3-9b14-2606927b1e21

	column PartId
		dataType: int64
		formatString: 0
		lineageTag: db9edd05-340b-4661-a6cf-041ccb9cff85
		summarizeBy: none
		sourceColumn: PartId

		annotation SummarizationSetBy = Automatic

	column Id
		dataType: int64
		formatString: 0
		lineageTag: c00bf2d3-fed0-4db5-b242-029f4ee23ac3
		summarizeBy: count
		sourceColumn: Id

		annotation SummarizationSetBy = Automatic

	column Name
		dataType: string
		lineageTag: 3884f3cd-7f30-43c2-9f24-2fb1390dc303
		summarizeBy: none
		sourceColumn: Name

		annotation SummarizationSetBy = Automatic

	column DaysCoverage
		dataType: double
		lineageTag: 15491c73-c1e4-4f87-ba8a-40a7e44ad004
		summarizeBy: sum
		sourceColumn: DaysCoverage

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column StartDate
		dataType: dateTime
		formatString: Short Date
		lineageTag: fb01b6cb-0d07-4423-9e47-7e2a404470bd
		summarizeBy: none
		sourceColumn: StartDate

		variation Variation
			isDefault
			relationship: 2ed904a3-6378-42c9-a232-f80b7954fb23
			defaultHierarchy: LocalDateTable_40671710-21f5-4bec-b133-07c964302cfa.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column EndDate
		dataType: dateTime
		formatString: Short Date
		lineageTag: d0a95d3a-1e67-4b5f-a4fa-a17ecf8936ab
		summarizeBy: none
		sourceColumn: EndDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column UnitsCoverage
		dataType: double
		formatString: #,0
		lineageTag: e54d8ab9-c879-426e-b240-6dc3e105e681
		summarizeBy: sum
		sourceColumn: UnitsCoverage

		annotation SummarizationSetBy = Automatic

	column ZoneType
		dataType: int64
		formatString: 0
		lineageTag: 3da2f9a1-9391-4cd4-ac85-a081f14a29b3
		summarizeBy: sum
		sourceColumn: ZoneType

		annotation SummarizationSetBy = Automatic

	column NumOfParts
		dataType: int64
		formatString: 0
		lineageTag: 6f5e3349-0cae-42ea-aca4-d2bfb16f5204
		summarizeBy: sum
		sourceColumn: NumOfParts

		annotation SummarizationSetBy = Automatic

	column Unit
		dataType: string
		lineageTag: 87b8a487-2078-44ed-b36e-3e9de2852859
		summarizeBy: none
		sourceColumn: Unit

		annotation SummarizationSetBy = Automatic

	column 'Units Coverage Val'
		dataType: double
		lineageTag: f8d85f1d-e885-44ea-b733-26db17e7ce0a
		summarizeBy: sum
		sourceColumn: Units Coverage Val

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition AdjustmentFactors = m
		mode: import
		queryGroup: AdjustmentFactors
		source =
				let
				    Source = Sql.Database(#"Server", #"Database",[Query="SELECT PartId,Id, Name, DaysCoverage, StartDate, EndDate, UnitsCoverage, ZoneType, NumOfParts FROM CycleDayAdjustmentFactors With (NoLock) left join PartCycleDayAdjustmentFactors With (NoLock) on Id=CycleDayAdjustmentFactorId where IsIntelligentAdjustment= 1"]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"StartDate", type date}, {"EndDate", type date}}),
				    #"Merged Queries" = Table.NestedJoin(#"Changed Type", {"PartId"}, PartsPakagings, {"PartId"}, "PartsPackagings", JoinKind.LeftOuter),
				    #"Expanded PartsPackagings" = Table.ExpandTableColumn(#"Merged Queries", "PartsPackagings", {"Quantity", "Unit"}, {"Quantity", "Unit"}),
				    #"Added Custom" = Table.AddColumn(#"Expanded PartsPackagings", "Units Coverage Val", each [UnitsCoverage]/[Quantity],type number),
				    #"Removed Columns" = Table.RemoveColumns(#"Added Custom",{"Quantity"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

