table Calendar
	lineageTag: 8739d516-e081-41cb-9542-29d38f48c89a

	measure Today = TODAY()
		formatString: General Date
		lineageTag: 14f77923-c19f-4a8a-8d8a-7318848087d7

	column 'Start Of Month'
		dataType: dateTime
		formatString: Short Date
		lineageTag: a087fe8f-d45b-4586-b02b-d4f003d26aea
		summarizeBy: none
		sourceColumn: Start Of Month

		variation Variation
			isDefault
			relationship: 72935d21-9a8b-4950-ac68-3cc353223623
			defaultHierarchy: LocalDateTable_038d8b69-f19c-458a-ad1f-0f6964d45ff1.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Start Of Year'
		dataType: dateTime
		formatString: yyyy
		lineageTag: 72888fd5-6c56-4468-83ed-4bd37368f430
		summarizeBy: none
		sourceColumn: Start Of Year

		variation Variation
			isDefault
			relationship: e3492746-a7b2-4df0-b1c3-9de97f453193
			defaultHierarchy: LocalDateTable_898b9078-151e-47d5-b6a9-c7d14ccd55b7.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Start Of Quarter'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 935a27e3-097c-4693-a7f9-e9fb2e112af0
		summarizeBy: none
		sourceColumn: Start Of Quarter

		variation Variation
			isDefault
			relationship: dec94696-b8f1-4c72-8161-1de39e28ba20
			defaultHierarchy: LocalDateTable_b7fda9cd-8d4b-41b5-ac1a-e0317638f854.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Date
		dataType: dateTime
		formatString: Short Date
		lineageTag: 80447adf-becf-43bb-b349-db91d6e3bdab
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: 9fd012fd-1bfb-41c9-8032-8d081597c589
			defaultHierarchy: LocalDateTable_278399d7-4d92-41de-8bcf-465b1027c5b7.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Start Of Week'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 8e0c9ff3-5086-4f9e-bb60-53bb319249ec
		summarizeBy: none
		sourceColumn: Start Of Week

		variation Variation
			isDefault
			relationship: 8f42483a-78fa-4537-8fda-111cc1180cf0
			defaultHierarchy: LocalDateTable_2221ea6a-06fd-42db-9a2a-fe1c5f8ab6ab.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Date_ = 'Calendar'[Date]
		formatString: General Date
		lineageTag: 68e6412c-07eb-4d26-aeb3-33f1d6993209
		summarizeBy: none

		variation Variation
			isDefault
			relationship: baa32286-1aa6-43f2-95c1-e40e88514258
			defaultHierarchy: LocalDateTable_0a980c2c-ac05-448d-ad29-7a3f3e87cbd4.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	partition Calendar-edbf028b-90ad-4ffe-aac9-8feada260198 = m
		mode: import
		queryGroup: Calendar
		source =
				let
				    Source = StartDateAndEndDateForCalendar,
				    #"Added Custom" = Table.AddColumn(Source, "Start Of Week", each Date.StartOfWeek([Date], Day.Monday)),
				    #"Personnalisée ajoutée2" = Table.AddColumn(#"Added Custom", "Start Of Month", each Date.StartOfMonth([Date])),
				    #"Personnalisée ajoutée6" = Table.AddColumn(#"Personnalisée ajoutée2", "Start Of Year", each Date.StartOfYear([Date])),
				    #"Personnalisée ajoutée7" = Table.AddColumn(#"Personnalisée ajoutée6", "Start Of Quarter", each Date.StartOfQuarter([Date])),
				    #"Type modifié2" = Table.TransformColumnTypes(#"Personnalisée ajoutée7",{{"Start Of Year", type date}, {"Start Of Month", type date}, {"Start Of Quarter", type date}, {"Start Of Week", type date}})
				in
				    #"Type modifié2"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

