table Parts
	lineageTag: 34ba17aa-65d0-4f35-9129-2ba0269d456d

	column Id
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 3274a6ce-44f3-4403-bd8c-ee00fbb20c55
		summarizeBy: none
		sourceColumn: Id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column PartNumber
		dataType: string
		lineageTag: ecbd7cbb-61dc-45a4-aba8-7d9f9ef4e123
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: PartNumber

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Location
		dataType: string
		lineageTag: 07a56b93-0f14-4c44-9a95-c09240e73236
		summarizeBy: none
		sourceColumn: Location

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column RawMaterialsCost
		dataType: double
		lineageTag: f74b8bbd-7e70-44b6-9d2f-74892a0ee849
		summarizeBy: sum
		sourceColumn: RawMaterialsCost

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Part_Numb_Location
		dataType: string
		lineageTag: 980eb026-7040-46e5-9136-0e7126b68a24
		summarizeBy: none
		sourceColumn: Part_Numb_Location

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Description
		dataType: string
		lineageTag: c8c2cddd-5ca8-49cc-8d8a-f94ca212b93e
		summarizeBy: none
		sourceColumn: Description

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column PlannerCode
		dataType: string
		lineageTag: 8bd40362-4faa-42c0-9fa3-122b4e7fe7a4
		summarizeBy: none
		sourceColumn: PlannerCode

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Vendor
		dataType: string
		lineageTag: 05594193-be48-48bc-a80c-04271c9bc80f
		summarizeBy: none
		sourceColumn: Vendor

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Notes
		dataType: string
		lineageTag: c71281e1-d972-473e-b168-4dd3e6a7facf
		summarizeBy: none
		sourceColumn: Notes

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Revision
		dataType: string
		lineageTag: e14d8cb1-9bc3-407a-a7c4-dde56b0753f4
		summarizeBy: none
		sourceColumn: Revision

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column InventoryPlanning
		dataType: string
		lineageTag: 6cb064ec-2782-4837-9467-50a34bf8446d
		summarizeBy: none
		sourceColumn: InventoryPlanning

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DailyUsageType
		dataType: string
		lineageTag: 73b8a842-59e8-4c9a-ae36-36d40d2f8018
		summarizeBy: none
		sourceColumn: DailyUsageType

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DisableAutoProfile
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: e2decbc3-1716-4b23-a79c-a9e6f5c3bd36
		summarizeBy: none
		sourceColumn: DisableAutoProfile

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column MaterialType
		dataType: string
		lineageTag: d86c2382-91e0-4372-84a4-10eac3c54b37
		summarizeBy: none
		sourceColumn: MaterialType

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column TopOfGreen
		dataType: double
		lineageTag: d05836fb-33bc-4ccc-85a2-941c5a76114b
		summarizeBy: sum
		sourceColumn: TopOfGreen

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TopOfYellow
		dataType: double
		lineageTag: f7ba6cde-afc8-4d51-b49a-871b959ddd22
		summarizeBy: sum
		sourceColumn: TopOfYellow

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TopOfRed
		dataType: double
		lineageTag: 78b611dc-c61e-4809-8c06-0880979bb33b
		summarizeBy: sum
		sourceColumn: TopOfRed

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column OnHandQty
		dataType: double
		lineageTag: f5991127-b812-4ee3-8c1d-cd0ac3ea71e5
		summarizeBy: sum
		sourceColumn: OnHandQty

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ForecastedDailyUsage
		dataType: double
		lineageTag: 4de0e633-c049-450c-bcf6-c6e11edcda7c
		summarizeBy: sum
		sourceColumn: ForecastedDailyUsage

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column EffectiveDailyUsage
		dataType: double
		lineageTag: 9e85efef-9d97-47ed-a660-31f3c7ba25b2
		summarizeBy: sum
		sourceColumn: EffectiveDailyUsage

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column AverageDailyUsage
		dataType: double
		lineageTag: 35973939-1967-4a29-a512-c78d51238fa6
		summarizeBy: sum
		sourceColumn: AverageDailyUsage

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column RPlusLeadTime
		dataType: int64
		formatString: 0
		lineageTag: 6dae7d06-fcb7-4721-b8c1-df20cda5e430
		summarizeBy: sum
		sourceColumn: RPlusLeadTime

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column EffectiveLeadTime
		dataType: int64
		formatString: 0
		lineageTag: 0e450ab6-4bf2-43ef-a274-b70b2defae26
		summarizeBy: sum
		sourceColumn: EffectiveLeadTime

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column MTO-MTS = if('Parts'[InventoryMethod]=0,"MTO","MTS")
		lineageTag: 5bd961ef-3360-446e-ad3e-6dccb9da1110
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Url_Workbench
		dataType: string
		lineageTag: 96da6d06-5763-40da-9e7c-020f203f63f7
		dataCategory: WebUrl
		summarizeBy: none
		sourceColumn: Url_Workbench

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Url_SnOP
		dataType: string
		lineageTag: b0e38adc-d6d5-4114-bc6c-5f173721b40f
		dataCategory: WebUrl
		summarizeBy: none
		sourceColumn: Url_SnOP

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column one
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 969f368f-6457-45e7-8a7e-e1555e399f42
		summarizeBy: sum
		sourceColumn: one

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Database_Name
		dataType: string
		lineageTag: 4a9a3beb-3a8a-4d2e-b8d7-0e6c19358942
		summarizeBy: none
		sourceColumn: Database_Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column PartType
		dataType: string
		lineageTag: f4fcd688-a93c-447b-a9cf-6c3cb909f867
		summarizeBy: none
		sourceColumn: PartType

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UserDefined1
		dataType: string
		lineageTag: cf63ffa0-1c63-4797-a42b-588bfda53dc1
		summarizeBy: none
		sourceColumn: UserDefined1

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UserDefined2
		dataType: string
		lineageTag: a97f6adf-b082-4a8b-b387-e0830db40a31
		summarizeBy: none
		sourceColumn: UserDefined2

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UserDefined3
		dataType: string
		lineageTag: dbcfcf9b-a022-41b1-82bd-77380bec0f90
		summarizeBy: none
		sourceColumn: UserDefined3

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UserDefined4
		dataType: string
		lineageTag: 9b85a5e8-ebb0-434b-8367-d88438b3b25d
		summarizeBy: none
		sourceColumn: UserDefined4

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UserDefined5
		dataType: string
		lineageTag: 0c320efe-6342-4595-97b9-69393b18fa18
		summarizeBy: none
		sourceColumn: UserDefined5

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UserDefined6
		dataType: string
		lineageTag: 1a3cc0fd-2ba9-40da-8064-639d67eb8ce3
		summarizeBy: none
		sourceColumn: UserDefined6

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UserDefined7
		dataType: string
		lineageTag: 2870de29-9fd3-4808-b338-622527005861
		summarizeBy: none
		sourceColumn: UserDefined7

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UserDefined8
		dataType: string
		lineageTag: badcb6e5-3067-4180-bd32-c2a4a1ff5944
		summarizeBy: none
		sourceColumn: UserDefined8

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UserDefined9
		dataType: string
		lineageTag: 2a9fc502-75ce-4c8b-bcb4-794f3f84535a
		summarizeBy: none
		sourceColumn: UserDefined9

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UserDefined10
		dataType: string
		lineageTag: 496558f1-7a71-47b3-9ea1-0af07156b59a
		summarizeBy: none
		sourceColumn: UserDefined10

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UserDefined11
		dataType: string
		lineageTag: fd492f45-62a1-4e30-9506-a4e4a05d1bbf
		summarizeBy: none
		sourceColumn: UserDefined11

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UserDefined12
		dataType: string
		lineageTag: 3c7a3919-6c12-4235-8db4-e1f4b441ea80
		summarizeBy: none
		sourceColumn: UserDefined12

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UserDefined13
		dataType: string
		lineageTag: 41dfcf34-4ece-4178-9b77-affd513bebd7
		summarizeBy: none
		sourceColumn: UserDefined13

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UserDefined14
		dataType: string
		lineageTag: 2bbfb223-0f09-440d-b2c4-1a84558a6710
		summarizeBy: none
		sourceColumn: UserDefined14

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UserDefined15
		dataType: string
		lineageTag: 91e0a7cb-0373-458b-979f-19bf04d5d942
		summarizeBy: none
		sourceColumn: UserDefined15

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UserDefined16
		dataType: string
		lineageTag: 06a3a09c-a02a-4d92-8c77-82d665b92555
		summarizeBy: none
		sourceColumn: UserDefined16

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column AD_Key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 5a0f2877-966f-4358-ae68-98e3b10cac97
		summarizeBy: none
		sourceColumn: AD_Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Vendoridentifier
		dataType: string
		lineageTag: 0144d3ce-1c6c-4876-93a3-05c1f6cdf288
		summarizeBy: none
		sourceColumn: Vendoridentifier

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column OrderMinimumQty
		dataType: double
		lineageTag: 012f1dcd-fbb7-4a7d-924e-957db4481a27
		summarizeBy: sum
		sourceColumn: OrderMinimumQty

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Inventory Method' = ```
			
			                 IF( 'Parts'[InventoryMethod]=1,"Buffer",'Parts'[InventoryPlanning])
			```
		lineageTag: 61a95b9d-84f0-4318-8e88-8c058a048db4
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column BoMType
		dataType: string
		lineageTag: 52ba24cc-d450-4c63-8393-b5daf9130b72
		summarizeBy: none
		sourceColumn: BoMType

		annotation SummarizationSetBy = Automatic

	column Priority
		dataType: string
		lineageTag: 46216f43-33ea-4240-8b38-c8deac556b4f
		summarizeBy: none
		sourceColumn: Priority

		annotation SummarizationSetBy = Automatic

	column AlertSeverity
		dataType: string
		lineageTag: b891e7dc-bdab-4370-a18d-ec8d17c9d5cf
		summarizeBy: none
		sourceColumn: AlertSeverity

		annotation SummarizationSetBy = Automatic

	column AlertType
		dataType: string
		lineageTag: 5ad5e009-44a1-45b4-8985-161560a9e5d2
		summarizeBy: none
		sourceColumn: AlertType

		annotation SummarizationSetBy = Automatic

	column AlertDate
		dataType: dateTime
		formatString: General Date
		lineageTag: 824c885c-0f46-4bc8-ad5b-8369f12ba58f
		summarizeBy: none
		sourceColumn: AlertDate

		variation Variation
			isDefault
			relationship: 1b135d1e-e09b-4c40-b9fe-ebf879cc5239
			defaultHierarchy: LocalDateTable_0b645bd7-d48f-46e5-91e7-be1e82166830.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column SupplyOrderQty
		dataType: double
		lineageTag: 8b2d51d3-dfa5-4738-ba58-90a8c0addbe4
		summarizeBy: sum
		sourceColumn: SupplyOrderQty

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DemandAllocationQty
		dataType: double
		lineageTag: e65279d3-4c54-4017-8037-1d43dad67164
		summarizeBy: sum
		sourceColumn: DemandAllocationQty

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column InventoryMethod
		dataType: int64
		formatString: 0
		lineageTag: 32c9e842-03e4-40dc-bcf9-68b82238c048
		summarizeBy: sum
		sourceColumn: InventoryMethod

		annotation SummarizationSetBy = Automatic

	column UnitOfMeasure
		dataType: string
		lineageTag: a6af494b-5a48-48ee-9233-bba518080d6b
		summarizeBy: none
		sourceColumn: UnitOfMeasure

		annotation SummarizationSetBy = Automatic

	partition Parts-c69e773b-3d8c-4c2b-8128-ad8416eb28d7 = m
		mode: import
		queryGroup: Sources
		source =
				let
				     Source = Sql.Database(Server, Database, [Query="SELECT DB_NAME() AS Database_Name,Id, AlertSeverity, AlertType, AlertDate,PartNumber,PartType, Revision, Location, Description,InventoryMethod, InventoryPlanning,DailyUsageType, DisableAutoProfile, RawMaterialsCost,PlannerCode, BoMType,MaterialType, Notes, OrderMinimumQty,Vendor,Vendoridentifier,TopOfGreen,TopOfYellow,TopOfRed,OnHandQty,ForecastedDailyUsage, EffectiveDailyUsage, AverageDailyUsage, RPlusLeadTime, SupplyOrderQty, DemandAllocationQty,EffectiveLeadTime,Priority,UnitOfMeasure,UserDefined1,UserDefined2,UserDefined3,UserDefined4,UserDefined5,UserDefined6,UserDefined7,UserDefined8,UserDefined9,UserDefined10,UserDefined11,UserDefined12,UserDefined13,UserDefined14,UserDefined15,UserDefined16, 1 as one FROM report.Parts With (NoLock)"]),
				    #"Replaced Value" = Table.ReplaceValue(Source,".App","",Replacer.ReplaceText,{"Database_Name"}),
				    #"Type modifié" = Table.TransformColumnTypes(#"Replaced Value",{{"InventoryMethod", type text}}),
				    #"Personnalisée ajoutée2" = Table.AddColumn(#"Type modifié", "Personnalisé", each if [InventoryMethod] = "NB" or [InventoryMethod] = "Non-Buffered" or [InventoryMethod] = "Lead Time Managed" or [InventoryMethod] = "LTM" then 0 else if [InventoryMethod] = "0" then 0 else 1, Int64.Type),
				    #"Colonnes supprimées" = Table.RemoveColumns(#"Personnalisée ajoutée2",{"InventoryMethod"}),
				    #"Colonnes renommées" = Table.RenameColumns(#"Colonnes supprimées",{{"Personnalisé", "InventoryMethod"}}),
				    // Source = Sql.Database(Server, Database, [Query="SELECT Id, PartNumber,PartType, Revision, Location, Description,InventoryMethod, InventoryPlanning,DailyUsageType, DisableAutoProfile, RawMaterialsCost,PlannerCode, MaterialType, Notes, Vendor,TopOfGreen,TopOfYellow,TopOfRed,OnHandQty,ForecastedDailyUsage, EffectiveDailyUsage, AverageDailyUsage, RPlusLeadTime, EffectiveLeadTime,UserDefined1,UserDefined2,UserDefined3,UserDefined4,UserDefined5,UserDefined6,UserDefined7,UserDefined8,UserDefined9,UserDefined10,UserDefined11,UserDefined12,UserDefined13,UserDefined14,UserDefined15,UserDefined16, 1 as one FROM report.Parts", CommandTimeout=#duration(0, 1, 30, 0)]),
				    #"Added Custom" = Table.AddColumn(#"Colonnes renommées", "Part_Numb_Location", each Text.Combine({[PartNumber], "-", [Location],"-",[Revision]}),type text),
				    #"Index ajouté" = Table.AddColumn(#"Added Custom", "AD_Key", each 1,Int64.Type),
				    Url_Workbench = Table.AddColumn(#"Index ajouté", "Url_Workbench", each "https://" & [Database_Name] &"."&URL&"/Workbench?partnumber=" & [PartNumber] & "&location=" & [Location],type text),
				    Url_SnOP = Table.AddColumn(Url_Workbench, "Url_SnOP", each "https://" & [Database_Name] &"."&URL&"/simulation/view/projectedsupply?partnumber=" & [PartNumber] & "&location=" & [Location],type text),
				    #"Merged Queries" = Table.NestedJoin(Url_SnOP, {"Id"}, #"PartsS&OP", {"PartId"}, "PartsS&OP", JoinKind.Inner),
				    #"Removed Columns" = Table.RemoveColumns(#"Merged Queries",{"PartsS&OP"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

