table ResourceCalendars
	lineageTag: 35e8e6db-198a-482c-8edd-3d5b4c01bc79

	column ResourceId
		dataType: int64
		formatString: 0
		lineageTag: fa688178-c285-4c59-a1a9-0b22a3bd4555
		summarizeBy: none
		sourceColumn: ResourceId

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Duration_Hours
		dataType: double
		lineageTag: da75d2ca-9130-4788-bc20-376036bc5d34
		summarizeBy: sum
		sourceColumn: Duration_Hours

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SchedulingSetId
		dataType: int64
		formatString: 0
		lineageTag: 1e8e01bb-a72f-41c6-9dde-6e6eb5046c9b
		summarizeBy: none
		sourceColumn: SchedulingSetId

		annotation SummarizationSetBy = Automatic

	column Id
		dataType: int64
		formatString: 0
		lineageTag: cb3890f5-0db5-4fc2-88e2-7ececcd46da5
		summarizeBy: count
		sourceColumn: Id

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: c533978b-e3f5-4c8a-be50-c78c73ce00f6
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column AvailableCapacity
		dataType: int64
		formatString: 0
		lineageTag: f19ff595-22b3-4e6a-88d7-4207e41de419
		summarizeBy: sum
		sourceColumn: AvailableCapacity

		annotation SummarizationSetBy = Automatic

	column Capacity/Count = DIVIDE(ResourceCalendars[Duration_Hours],RELATED(Resources[Count]))
		lineageTag: d2432743-523a-41d2-ae46-e5561717c383
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition ResourceCalendars-b4f1efb5-1976-47f9-86ab-753a41cbdb6f = m
		mode: import
		queryGroup: RCCP
		source =
				let
				    Source = Sql.Database(Server, Database, [Query="SELECT t1.Id, t1.SchedulingSetId, t1.ResourceId,t1.AvailableCapacity, t1.Date FROM report.SchedulingFrameworks t1 With (NoLock) where t1.BeginningOfDay is not null and cast(t1.Date as date)>=CAST(GETDATE() AS DATE) and t1.date<='" & Date.ToText(Date.AddDays(Date.From(DateTime.LocalNow()),FutureDays),"yyyy-MM-dd") & "'"]),
				    #"Added Custom" = Table.AddColumn(Source, "Duration_Hours", each [AvailableCapacity]/60,type number),
				    #"Merged Queries" = Table.NestedJoin(#"Added Custom", {"SchedulingSetId"}, SchedulingSets, {"Id"}, "SchedulingSets", JoinKind.Inner),
				    #"Removed Columns" = Table.RemoveColumns(#"Merged Queries",{"SchedulingSets"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Removed Columns",{{"Date", type date}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navigation

