table RisksCriticalConstrainedMonthly
	lineageTag: 0b1d104d-77d9-4b70-af0f-31a635e00d7f

	column SimulationId
		dataType: int64
		formatString: 0
		lineageTag: 5718e65a-9b12-4861-9a5b-f80ab8a76e73
		summarizeBy: none
		sourceColumn: SimulationId

		annotation SummarizationSetBy = Automatic

	column Id
		dataType: int64
		formatString: 0
		lineageTag: af023e6b-241e-4e42-b250-497712faea5a
		summarizeBy: none
		sourceColumn: Id

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 28f8dbcf-0df0-4274-ae3f-8b80ed2addec
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column RisksCritical
		dataType: double
		lineageTag: e3f9d48b-7955-42d8-abcf-ed531850b8a7
		summarizeBy: sum
		sourceColumn: RisksCritical

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition RisksCriticalConstrainedMonthly = m
		mode: import
		queryGroup: 'S&OP report Part\Risks'
		source =
				let
				    Source = Table.SelectColumns(SimulationPartForecastsConstrainedAll,{"Id", "SimulationId", "Date", "RisksCritical"}),
				    #"Filtered Rows" = Table.SelectRows(Source, each ([RisksCritical] = 1)),
				    #"Added Custom" = Table.AddColumn(#"Filtered Rows", "Start Of Month", each Date.StartOfMonth([Date]),type date),
				    #"Grouped Rows" = Table.Group(#"Added Custom", {"SimulationId", "Id", "Start Of Month"}, {{"RisksCritical", each List.Sum([RisksCritical]), type number}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Grouped Rows",{{"Start Of Month", "Date"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

