table RisksYellowWeekly
	lineageTag: d70aa056-a16d-4296-a53e-a6fe99c51566

	column Id
		dataType: int64
		formatString: 0
		lineageTag: 2527ae8b-fb4f-4a38-b503-409c373b38cb
		summarizeBy: none
		sourceColumn: Id

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 6fd32a31-de9a-4d0f-97b3-7bc4d231a92b
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column RisksYellow
		dataType: double
		formatString: 0
		lineageTag: e9a6738a-542f-4f71-a79e-61a871da540f
		summarizeBy: sum
		sourceColumn: RisksYellow

		annotation SummarizationSetBy = Automatic

	column SimulationId
		dataType: int64
		formatString: 0
		lineageTag: 08c1b8cf-8a8e-495e-9897-68d53e5c8325
		summarizeBy: none
		sourceColumn: SimulationId

		annotation SummarizationSetBy = Automatic

	partition RisksYellowWeekly = m
		mode: import
		queryGroup: 'S&OP report Part\Risks'
		source =
				let
				    Source = Table.SelectColumns(SimulationPartForecastsWeeklyAll,{"Id", "Date", "RisksYellow", "SimulationId"}),
				    #"Filtered Rows" = Table.SelectRows(Source, each ([RisksYellow] <> 0))
				in
				    #"Filtered Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

