table RisksYellowMonthly
	lineageTag: b499956b-c53a-4cdb-861f-5aba04075544

	column Id
		dataType: int64
		formatString: 0
		lineageTag: 34da67b3-66e9-44f1-881f-bf7f86176386
		summarizeBy: none
		sourceColumn: Id

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 5ab4e046-5627-410f-af9b-026c6fb3fe5a
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column RisksYellow
		dataType: int64
		formatString: 0
		lineageTag: 2fb598e2-d836-462f-93d6-2db16aaf6ad7
		summarizeBy: sum
		sourceColumn: RisksYellow

		annotation SummarizationSetBy = Automatic

	column SimulationId
		dataType: int64
		formatString: 0
		lineageTag: 6522c02a-7c61-44bb-981a-c02c746bfb73
		summarizeBy: none
		sourceColumn: SimulationId

		annotation SummarizationSetBy = Automatic

	partition RisksYellowMonthly = m
		mode: import
		queryGroup: 'S&OP report Part\Risks'
		source =
				let
				    Source = Table.SelectColumns(SimulationPartForecastsMonthlyAll,{"Id", "Date", "RisksYellow", "SimulationId"}),
				    #"Filtered Rows" = Table.SelectRows(Source, each ([RisksYellow] <> 0))
				in
				    #"Filtered Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

