table RisksRedWeekly
	lineageTag: 08110890-2c96-467f-b794-41a8ccbff651

	column Id
		dataType: int64
		formatString: 0
		lineageTag: 9372a23b-49bf-4cbd-a0b6-7d975375ea56
		summarizeBy: none
		sourceColumn: Id

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 16a725b1-c53d-4811-aa04-ccabef0f9749
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column RisksRed
		dataType: double
		formatString: 0
		lineageTag: 27869d9c-db85-4a26-a12a-312c2d7a2a35
		summarizeBy: sum
		sourceColumn: RisksRed

		annotation SummarizationSetBy = Automatic

	column SimulationId
		dataType: int64
		formatString: 0
		lineageTag: d22d650d-7056-45bd-a95b-b868747a7484
		summarizeBy: none
		sourceColumn: SimulationId

		annotation SummarizationSetBy = Automatic

	partition RisksRedWeekly = m
		mode: import
		queryGroup: 'S&OP report Part\Risks'
		source =
				let
				    Source = Table.SelectColumns(SimulationPartForecastsWeeklyAll,{"Id", "Date", "RisksRed", "SimulationId"}),
				    #"Filtered Rows" = Table.SelectRows(Source, each ([RisksRed] <> 0))
				in
				    #"Filtered Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

