table RisksCriticalConstrainedWeekly
	lineageTag: c6205fc3-a3d1-41bf-b8fd-f399121c07de

	column SimulationId
		dataType: int64
		formatString: 0
		lineageTag: 778517dd-29d1-4279-8b4a-d7f21698e854
		summarizeBy: none
		sourceColumn: SimulationId

		annotation SummarizationSetBy = Automatic

	column Id
		dataType: int64
		formatString: 0
		lineageTag: 294e9491-4352-4265-b5e1-ca95e3032e72
		summarizeBy: none
		sourceColumn: Id

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 029b9b43-033b-49ab-92f0-d324e0af4eb8
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column RisksCritical
		dataType: double
		lineageTag: 7d65275a-dce1-4c7f-bfec-b25c9a47f34d
		summarizeBy: sum
		sourceColumn: RisksCritical

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition RisksCriticalConstrainedWeekly = m
		mode: import
		queryGroup: 'S&OP report Part\Risks'
		source =
				let
				    Source = Table.SelectColumns(SimulationPartForecastsConstrainedAll,{"Id", "SimulationId", "Date", "RisksCritical"}),
				    #"Filtered Rows" = Table.SelectRows(Source, each ([RisksCritical] = 1)),
				    #"Added Custom" = Table.AddColumn(#"Filtered Rows", "Start Of Week", each Date.StartOfWeek([Date], Day.Monday),type date),
				    #"Grouped Rows" = Table.Group(#"Added Custom", {"SimulationId", "Id", "Start Of Week"}, {{"RisksCritical", each List.Sum([RisksCritical]), type number}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Grouped Rows",{{"Start Of Week", "Date"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

