table RisksCriticalWeekly
	lineageTag: d0f485b9-ac03-4fb6-a2d3-8eb78863820c

	column Id
		dataType: int64
		formatString: 0
		lineageTag: 86257f95-9927-467b-9f62-23d79d2439f8
		summarizeBy: none
		sourceColumn: Id

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: a8668f8d-a411-4153-abc1-1403dc77ef89
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column RisksCritical
		dataType: double
		formatString: 0
		lineageTag: b0d40958-d320-4676-bec7-38ffb21dde6b
		summarizeBy: sum
		sourceColumn: RisksCritical

		annotation SummarizationSetBy = Automatic

	column SimulationId
		dataType: int64
		formatString: 0
		lineageTag: 7699be9f-8121-41b4-999e-bc4fab953947
		summarizeBy: none
		sourceColumn: SimulationId

		annotation SummarizationSetBy = Automatic

	partition RisksCriticalWeekly = m
		mode: import
		queryGroup: 'S&OP report Part\Risks'
		source =
				let
				    Source = Table.SelectColumns(SimulationPartForecastsWeeklyAll,{"Id", "Date", "RisksCritical", "SimulationId"}),
				    #"Filtered Rows" = Table.SelectRows(Source, each ([RisksCritical] <> 0))
				in
				    #"Filtered Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

