table RisksRedConstrainedMonthly
	lineageTag: d3af708d-d616-4191-ade7-5a8e773b3346

	column SimulationId
		dataType: int64
		formatString: 0
		lineageTag: 0b5e24c6-8be6-46ab-8208-09ce7180c3ee
		summarizeBy: none
		sourceColumn: SimulationId

		annotation SummarizationSetBy = Automatic

	column Id
		dataType: int64
		formatString: 0
		lineageTag: 5d37424b-f172-4383-a7c0-1b83a8c1d0aa
		summarizeBy: none
		sourceColumn: Id

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 0cd7066d-dca6-4aad-9eef-2d7cc005016e
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column RisksRed
		dataType: double
		lineageTag: cf73d6d0-ccb5-4cb7-b572-6766eedd6472
		summarizeBy: sum
		sourceColumn: RisksRed

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition RisksRedConstrainedMonthly = m
		mode: import
		queryGroup: 'S&OP report Part\Risks'
		source =
				let
				    Source = Table.SelectColumns(SimulationPartForecastsConstrainedAll,{"Id", "SimulationId", "Date", "RisksRed"}),
				    #"Filtered Rows" = Table.SelectRows(Source, each ([RisksRed] = 1)),
				    #"Added Custom" = Table.AddColumn(#"Filtered Rows", "Start Of Month", each Date.StartOfMonth([Date]),type date),
				    #"Grouped Rows" = Table.Group(#"Added Custom", {"SimulationId", "Id", "Start Of Month"}, {{"RisksRed", each List.Sum([RisksRed]), type number}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Grouped Rows",{{"Start Of Month", "Date"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

