table RLS_VendorIdentifierValue
	isHidden
	lineageTag: fc731990-00cb-4e64-a03d-a3241c5c54a1

	column FieldValue
		dataType: string
		isHidden
		lineageTag: 657c5c93-9b65-44ec-bf9e-d92ae6f7660f
		summarizeBy: none
		sourceColumn: FieldValue

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column FilterKind
		dataType: int64
		formatString: 0
		lineageTag: 12a864f7-1e2f-4a86-a171-e00535850e29
		summarizeBy: sum
		sourceColumn: FilterKind

		annotation SummarizationSetBy = Automatic

	partition RLS_VendorIdentifierValue = m
		mode: import
		queryGroup: RLS
		source =
				let
				    Source = RLS_UserResourceFilters,
				    #"Filtered Rows" = Table.SelectRows(Source, each ([FieldName] = "VendorIdentifier")and ([FilterKind] <> 0)),
				    #"Colonnes supprimées" = Table.RemoveColumns(#"Filtered Rows",{"Email", "FieldName"}),
				    #"Doublons supprimés" = Table.Distinct(#"Colonnes supprimées"),
				    #"Filtered Rows1" = Table.SelectRows(#"Doublons supprimés", each ([FieldValue] <> ""))
				in
				    #"Filtered Rows1"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

