table RLS_PlannerCode
	isHidden
	lineageTag: 067d09c2-4c20-4d64-9814-9d58b28bb1bf

	column Email
		dataType: string
		isHidden
		lineageTag: e5935e09-8d26-4711-a914-c46be39ed8f3
		summarizeBy: none
		sourceColumn: Email

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column FieldName
		dataType: string
		isHidden
		lineageTag: 6234c31c-b2eb-4d53-a1c8-3ade7bce44c9
		summarizeBy: none
		sourceColumn: FieldName

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column FieldValue
		dataType: string
		isHidden
		lineageTag: 27c21043-6d9b-41e8-8f76-4d4f91201e57
		summarizeBy: none
		sourceColumn: FieldValue

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column FilterKind
		dataType: int64
		formatString: 0
		lineageTag: 5d209f80-2fff-4f74-a566-06f606fb2aa7
		summarizeBy: sum
		sourceColumn: FilterKind

		annotation SummarizationSetBy = Automatic

	partition RLS_PlannerCode = m
		mode: import
		queryGroup: RLS
		source =
				let
				    Source = #"RLS_UserResourceFilters",
				    #"Filtered Rows" = Table.SelectRows(Source, each ([FieldName] = "PlannerCode")and ([FilterKind] <> 0))
				in
				    #"Filtered Rows"

	changedProperty = IsHidden

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navigation

