table Simulations
	lineageTag: e2acf46e-259a-45e2-9d8c-6d68a8f7d63b

	measure Scenario_Measure = MAX(Simulations[Index])
		formatString: 0
		lineageTag: b881c01d-eeed-414b-a887-aad23d8e2774

	measure Scenario_Name = MAX(Simulations[ScenarioName])
		lineageTag: 2fce0e1c-8e22-4d28-8296-d87cd05303e4

	column Id
		dataType: double
		formatString: 0
		lineageTag: 4b16e76f-ec1b-463f-b842-1b3ebceb3d90
		summarizeBy: none
		sourceColumn: Id

		annotation SummarizationSetBy = Automatic

	column SchedulingSetId
		dataType: double
		formatString: 0
		lineageTag: 208a0dba-4400-4bbe-ab52-8d281af605db
		summarizeBy: none
		sourceColumn: SchedulingSetId

		annotation SummarizationSetBy = Automatic

	column ScenarioId
		dataType: double
		formatString: 0
		lineageTag: 1fe4e898-d8f6-4d23-92c0-301a55bdf0e8
		summarizeBy: count
		sourceColumn: ScenarioId

		annotation SummarizationSetBy = Automatic

	column ScenarioName
		dataType: string
		lineageTag: 5f0cdc6b-4a9c-456d-81c8-9f46c5e4ebb9
		summarizeBy: none
		sourceColumn: ScenarioName

		annotation SummarizationSetBy = Automatic

	column Index = ```
			
			IF(
			    Simulations[ScenarioName] = "History",
			    "Last Year",
			    FORMAT(Simulations[Index1], "0")
			)
			
			
			```
		lineageTag: 28bc38bf-906e-4db5-98b9-aa240088402e
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column AD_Key = 1
		formatString: 0
		lineageTag: c1610b9a-df64-4595-b275-c0063df89d8e
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Scenarions = "Scenario: "&Simulations[ScenarioName]
		lineageTag: 0b747999-85c7-4e17-b636-70faa4842f69
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Index1 =
			
			RANKX(
			    ALL('Simulations'),
			    'Simulations'[ScenarioId],
			    ,
			    ASC,
			    DENSE
			)
		formatString: 0
		lineageTag: 053033ac-a9d0-4eb3-a582-ea8f44884cf3
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition Simulations = m
		mode: import
		queryGroup: Scenarios
		source =
				let
				    Source = Sql.Database(#"Server", #"Database"),
				    dbo_Simulations1 = Source{[Schema="dbo",Item="Simulations"]}[Data],
				    #"Removed Other Columns" = Table.SelectColumns(dbo_Simulations1,{"Id", "SchedulingSetId", "ScenarioId"}),
				    #"Merged Queries" = Table.NestedJoin(#"Removed Other Columns", {"ScenarioId"}, Scenarios, {"Id"}, "dbo_Scenarios", JoinKind.LeftOuter),
				    #"Expanded dbo_Scenarios" = Table.ExpandTableColumn(#"Merged Queries", "dbo_Scenarios", {"Name"}, {"ScenarioName"}),
				    #"Appended Query" = Table.Combine({#"Expanded dbo_Scenarios", SimulationsH})
				in
				    #"Appended Query"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

