table SimulationPartForecastsDemandMonthly
	lineageTag: e10a7433-3f33-49fa-b7ad-8bfc02d6ac42

	column Id
		dataType: int64
		formatString: 0
		lineageTag: b119e08c-8523-4c98-b617-8e332ff36ffb
		summarizeBy: none
		sourceColumn: Id

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 3f4cf769-558c-4be9-8d51-aaeb2ea2485b
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column SimulationId
		dataType: double
		formatString: 0
		lineageTag: 6d33f941-f917-4908-8baf-d2e5f6b21f66
		summarizeBy: none
		sourceColumn: SimulationId

		annotation SummarizationSetBy = Automatic

	column Unit
		dataType: string
		lineageTag: 7f043e2b-1ae6-4c82-8ba1-ed6baf3df56d
		summarizeBy: none
		sourceColumn: Unit

		annotation SummarizationSetBy = Automatic

	column Demand
		dataType: double
		lineageTag: 6593b73f-2d9a-4a64-9077-57589a43b489
		summarizeBy: sum
		sourceColumn: Demand

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition SimulationPartForecastsDemandMonthly = m
		mode: import
		queryGroup: 'S&OP report Part\SimulationPartForecasts'
		source =
				let
				    Source = Table.SelectColumns(SimulationPartForecastsMonthlyAll,{"Id", "Date", "ProjectedDailyDemand", "SimulationId"}),
				    #"Filtered Rows" = Table.SelectRows(Source, each (([ProjectedDailyDemand])<> 0)),
				    #"Merged Queries" = Table.NestedJoin(#"Filtered Rows", {"Id"}, PartsPakagings, {"PartId"}, "PartsPakagings", JoinKind.LeftOuter),
				    #"Expanded PartsPakagings" = Table.ExpandTableColumn(#"Merged Queries", "PartsPakagings", {"Quantity", "Unit"}, {"Quantity", "Unit"}),
				    #"Added Custom" = Table.AddColumn(#"Expanded PartsPakagings", "Demand", each [ProjectedDailyDemand]/[Quantity], type number),
				    #"Removed Columns" = Table.RemoveColumns(#"Added Custom",{"ProjectedDailyDemand", "Quantity"}),
				    #"Appended Query" = Table.Combine({#"Removed Columns", HistoryDemandMonth_})
				in
				    #"Appended Query"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

