table SimulationPartForecastsWeekly
	lineageTag: 0262787e-219f-4d4c-b3d9-1bc7001ca98e

	column Id
		dataType: int64
		formatString: 0
		lineageTag: 0ec29d47-2040-4482-8991-b071f06df1bf
		summarizeBy: none
		sourceColumn: Id

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 8a9f99c6-797d-4a00-9921-70b956887a4f
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column SimulationId
		dataType: double
		formatString: 0
		lineageTag: 3b17fae2-9401-412f-8c74-7fa54e276425
		summarizeBy: none
		sourceColumn: SimulationId

		annotation SummarizationSetBy = Automatic

	column Quantity
		dataType: double
		lineageTag: 1ba6ce02-f5c8-417d-9cb1-9f04e0aa8ad3
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Unit
		dataType: string
		lineageTag: ff606c3c-371c-4eb6-9bf1-6df8173adbc5
		summarizeBy: none
		sourceColumn: Unit

		annotation SummarizationSetBy = Automatic

	column ProjectedInventory_Positive
		dataType: double
		formatString: 0
		lineageTag: cbc776c9-b795-49da-b379-8cdac76325db
		summarizeBy: sum
		sourceColumn: ProjectedInventory_Positive

		annotation SummarizationSetBy = Automatic

	column ProjectedInventory_Negative
		dataType: double
		formatString: 0
		lineageTag: 4524899c-78cf-4523-9f7e-c5ef159fd135
		summarizeBy: sum
		sourceColumn: ProjectedInventory_Negative

		annotation SummarizationSetBy = Automatic

	column EndWeekInventory
		dataType: double
		lineageTag: fd3fe40b-1d9d-413e-a8b9-8a4fb5bf156e
		summarizeBy: sum
		sourceColumn: EndWeekInventory

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Id_SimulationId_Date = [Id]&"_"&[SimulationId]&"_"&[Date]
		lineageTag: bf95fa35-192b-4ec9-9c69-539fe00b268a
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column ProjectedInventoryConstrainedNegative = IF(RELATED(SimulationPartForecastsConstrainedWeekly[Id])<>BLANK(),RELATED(SimulationPartForecastsConstrainedWeekly[ProjectedInventoryConstrainedNegative1])/SimulationPartForecastsWeekly[Quantity],SimulationPartForecastsWeekly[ProjectedInventory_Negative])
		lineageTag: cf03a98f-9240-4f3e-a424-e338d1e08980
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ProjectedInventoryConstrainedPositive = IF(RELATED(SimulationPartForecastsConstrainedWeekly[Id])<>BLANK(),RELATED(SimulationPartForecastsConstrainedWeekly[ProjectedInventoryConstrainedPositive1])/SimulationPartForecastsWeekly[Quantity],SimulationPartForecastsWeekly[ProjectedInventory_Positive])
		lineageTag: 55ddb7de-4521-4363-84e4-71c0d69c8a70
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column OpenOrdes_Purchase =
			
			VAR CurrentId = [Id_SimulationId]
			VAR CurrentPromise = [Date]
			VAR Qty=
			CALCULATE (
			    SUM ( SupplyOrders[SupplyQty] ),
			    FILTER (
			       SupplyOrders,AND(
			       AND( SupplyOrders[Id_SimulationId] = CurrentId
			            , AND(SupplyOrders[StartDate] < CurrentPromise,CurrentPromise<SupplyOrders[PromiseDate]) ),SupplyOrders[OrderType]="Purchase Order")
			    )
			)
			RETURN Qty/[Quantity]
		lineageTag: 3fc31f23-f423-40e4-8d4b-674c7f913dca
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Id_SimulationId = [Id]&"_"&[SimulationId]
		lineageTag: 448e5da2-0b0d-451e-b72f-ac9a2def45f5
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column OpenOrdes_Transfer =
			
			VAR CurrentId = [Id_SimulationId]
			VAR CurrentPromise = [Date]
			VAR Qty=
			CALCULATE (
			    SUM ( SupplyOrders[SupplyQty] ),
			    FILTER (
			       SupplyOrders,AND(
			       AND( SupplyOrders[Id_SimulationId] = CurrentId
			            , AND(SupplyOrders[StartDate] < CurrentPromise,CurrentPromise<SupplyOrders[PromiseDate]) ),SupplyOrders[OrderType]="Transfer Order")
			    )
			)
			RETURN Qty/[Quantity]
		lineageTag: c1c6995a-bf76-4d76-9dc5-6a358e9941d5
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column OpenOrdes_Work =
			
			VAR CurrentId = [Id_SimulationId]
			VAR CurrentPromise = [Date]
			VAR Qty=
			CALCULATE (
			    SUM ( SupplyOrders[SupplyQty] ),
			    FILTER (
			       SupplyOrders,AND(
			       AND( SupplyOrders[Id_SimulationId] = CurrentId
			            , AND(SupplyOrders[StartDate] < CurrentPromise,CurrentPromise<SupplyOrders[PromiseDate]) ),SupplyOrders[OrderType]="Work Order")
			    )
			)
			RETURN Qty/[Quantity]
		lineageTag: cd9bd9a7-7558-4726-98a1-e7a7e7d13dd4
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition SimulationPartForecastsWeekly = m
		mode: import
		queryGroup: 'S&OP report Part\SimulationPartForecasts'
		source =
				let
				    Source = Table.SelectColumns(SimulationPartForecastsWeeklyAll,{"Id", "Date",  "ProjectedInventory_Positive","EndWeekInventory", "ProjectedInventory_Negative",  "SimulationId"}),
				    #"Filtered Rows" = Table.SelectRows(Source, each (([ProjectedInventory_Negative]+[ProjectedInventory_Positive])<> 0)),
				    #"Merged Queries" = Table.NestedJoin(#"Filtered Rows", {"Id"}, PartsPakagings, {"PartId"}, "PartsPakagings", JoinKind.LeftOuter),
				    #"Expanded PartsPakagings" = Table.ExpandTableColumn(#"Merged Queries", "PartsPakagings", {"Quantity", "Unit"}, {"Quantity", "Unit"}),
				    #"Added Custom1" = Table.AddColumn(#"Expanded PartsPakagings", "Inv", each [ProjectedInventory_Positive]/[Quantity], type number),
				    #"Added Custom5" = Table.AddColumn(#"Added Custom1", "Inv-", each [ProjectedInventory_Negative]/[Quantity], type number),
				    #"Added Custom6" = Table.AddColumn(#"Added Custom5", "Custom", each [EndWeekInventory]/[Quantity], type number),
				    #"Removed Columns" = Table.RemoveColumns(#"Added Custom6",{ "ProjectedInventory_Negative", "ProjectedInventory_Positive", "EndWeekInventory"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{ {"Inv", "ProjectedInventory_Positive"}, {"Inv-", "ProjectedInventory_Negative"}, {"Custom", "EndWeekInventory"}}),
				    #"Appended Query" = Table.Combine({#"Renamed Columns", HistoryProjectedInventoryWeek_})
				in
				    #"Appended Query"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

