table SimulationPartForecasts_BufferItemsMonthly
	lineageTag: 9ec5dbea-4802-4c83-9395-39d2bf3624a1

	column Id
		dataType: int64
		formatString: 0
		lineageTag: e3ee0351-3ffa-4818-8c20-824e4d38e47c
		summarizeBy: none
		sourceColumn: Id

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Short Date
		lineageTag: c08a8310-062d-4ebd-ac43-987f72859aa6
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Unit
		dataType: string
		lineageTag: fcc27525-c952-414d-a22c-31e4439d3286
		summarizeBy: none
		sourceColumn: Unit

		annotation SummarizationSetBy = Automatic

	column 'Top Of Green'
		dataType: double
		lineageTag: fc8e997b-5e2a-4da5-919b-c853ed07bc4d
		summarizeBy: sum
		sourceColumn: Top Of Green

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Top Of Red'
		dataType: double
		lineageTag: 7b65a202-6cbd-40e1-ad68-a64858a20297
		summarizeBy: sum
		sourceColumn: Top Of Red

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Top Of Yellow'
		dataType: double
		lineageTag: bc31486c-f08c-408c-811a-a051f9d11c99
		summarizeBy: sum
		sourceColumn: Top Of Yellow

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SimulationId
		dataType: int64
		formatString: 0
		lineageTag: d821776e-1076-475d-a43b-5b388bc2eb68
		summarizeBy: none
		sourceColumn: SimulationId

		annotation SummarizationSetBy = Automatic

	column 'Projected EDU'
		dataType: double
		lineageTag: e4736dd4-229a-4b72-bfda-c2c510a2affc
		summarizeBy: sum
		sourceColumn: Projected EDU

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition SimulationPartForecasts_BufferItemsMonthly = m
		mode: import
		queryGroup: 'S&OP report Part\SimulationPartForecasts'
		source = ```
				let
				    Source = Sql.Database(Server, Database, [Query="SELECT 
				    Id, SimulationId,
				    EOMONTH(Date) AS Date, 
				    SUM(TopOfGreen) AS TopOfGreen, 
				    SUM(TopOfRed) AS TopOfRed, 
				    SUM(TopOfYellow) AS TopOfYellow , 
				    SUM(ProjectedEDU) AS ProjectedEDU
				FROM report.SimulationPartForecasts WITH (NOLOCK) 
				WHERE 
				    (TopOfGreen >0 or TopOfRed >0 or TopOfYellow >0 or ProjectedEDU >0) 
				    AND Date >= cast(GETDATE() as date)
				    AND Date <= '" & Date.ToText(Date.AddDays(Date.From(DateTime.LocalNow()), FutureDays), "yyyy-MM-dd") & "' 
				GROUP BY 
				    Id,SimulationId, EOMONTH(Date);
				"]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Date", type date}}),
				    #"Merged Queries" = Table.NestedJoin(#"Changed Type", {"Id"}, PartsPakagings, {"PartId"}, "PartsPakagings", JoinKind.LeftOuter),
				    #"Expanded PartsPakagings" = Table.ExpandTableColumn(#"Merged Queries", "PartsPakagings", {"Quantity", "Unit"}, {"Quantity", "Unit"}),
				    #"Added Custom" = Table.AddColumn(#"Expanded PartsPakagings", "Top Of Green", each [TopOfGreen]/[Quantity],type number),
				    #"Added Custom1" = Table.AddColumn(#"Added Custom", "Top Of Red", each [TopOfRed]/[Quantity],type number),
				    #"Added Custom2" = Table.AddColumn(#"Added Custom1", "Top Of Yellow", each [TopOfYellow]/[Quantity],type number),
				    #"Added Custom3" = Table.AddColumn(#"Added Custom2", "Projected EDU", each [ProjectedEDU]/[Quantity],type number),
				    #"Removed Columns" = Table.RemoveColumns(#"Added Custom3",{"TopOfGreen", "TopOfRed", "TopOfYellow", "Quantity", "ProjectedEDU"})
				in
				    #"Removed Columns"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

