table SupplyOrders
	lineageTag: 6ae9a473-4f17-4e4a-a647-6f77e7176484

	column Id
		dataType: int64
		formatString: 0
		lineageTag: b154d233-c853-494b-a202-89ba5bafcc2d
		summarizeBy: count
		sourceColumn: Id

		annotation SummarizationSetBy = Automatic

	column StartDate
		dataType: dateTime
		formatString: Short Date
		lineageTag: 5fe20d00-26cf-4c50-bb33-289ebe3f8b22
		summarizeBy: none
		sourceColumn: StartDate

		variation Variation
			isDefault
			relationship: b70796c6-85b1-45a2-a758-4072b4956f83
			defaultHierarchy: LocalDateTable_4f8f9d61-9917-409f-835c-dcce0874985e.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column PromiseDate
		dataType: dateTime
		formatString: Short Date
		lineageTag: d19c1d63-88c3-420b-a3c1-c294949993b1
		summarizeBy: none
		sourceColumn: PromiseDate

		variation Variation
			isDefault
			relationship: c1165552-452a-44a5-b56a-71871326a249
			defaultHierarchy: LocalDateTable_53e38d94-870a-4148-8479-ce16b2204cea.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column SchedulingDate
		dataType: dateTime
		formatString: Short Date
		lineageTag: d284c931-351f-4f13-b751-86ce93825baf
		summarizeBy: none
		sourceColumn: SchedulingDate

		variation Variation
			isDefault
			relationship: 69b0b56b-2c6f-4778-9911-3cdb44003eb4
			defaultHierarchy: LocalDateTable_e40c9651-592e-41a1-a399-b67401f7776f.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column SupplyQty
		dataType: double
		lineageTag: 3302316a-2197-4170-b5c6-e00b73a1151e
		summarizeBy: sum
		sourceColumn: SupplyQty

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PlannedReleaseDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 45fa4b8a-bb4c-4570-90ef-e38ade7929d3
		summarizeBy: none
		sourceColumn: PlannedReleaseDate

		variation Variation
			isDefault
			relationship: 790369df-9de0-4eca-9f04-6d5640979216
			defaultHierarchy: LocalDateTable_95891e77-12ae-433c-84dd-429cc83a5bdc.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column OrderType
		dataType: string
		lineageTag: 3ea7be2a-f7de-4462-8ed3-e70cbb8219f7
		summarizeBy: none
		sourceColumn: OrderType

		annotation SummarizationSetBy = Automatic

	column SimulationId
		dataType: int64
		formatString: 0
		lineageTag: 1bb4d564-7b03-4c91-9384-3025b6141087
		summarizeBy: count
		sourceColumn: SimulationId

		annotation SummarizationSetBy = Automatic

	column Id_SimulationId = [Id]&"_"&[SimulationId]
		lineageTag: 7993d04a-13c9-488b-a8b1-c691f2eabb89
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition SupplyOrders = m
		mode: import
		queryGroup: Supply
		source =
				let
				    Source = Sql.Database(Server, Database, [Query="
				    WITH
				    SchedulingSetsRCCP AS (
				        SELECT Id
				        FROM dbo.SchedulingSets
				        WHERE Type = 1
				    ),
				    SchedulingOrders1 AS (
				        SELECT t1.OrderNumber, t1.PartId, t1.PromiseDate
				        FROM report.SchedulingOrders t1
				        INNER JOIN SchedulingSetsRCCP t2
				            ON t1.SchedulingSetId = t2.Id
				    ),
				    SupplyByDay AS (
				    SELECT
				        Id,
				        [Date],
				        [OrderType],Firm_Projected,
				        OrderNumber,StartDate,Vendor,SimulationId,
				        SUM(Quantity) AS SupplyQty
				    FROM (
				        SELECT
				            SimulationPartId AS Id,case
				            when [OrderType] = 0
				    then 'Purchase Order'
				    when [OrderType] = 1
				    then 'Work Order'
				    else 'Transfer Order'
				    end as [OrderType],
				            OrderNumber,StartDate,
				            CAST(
				                CASE
				                    WHEN OrderReceiptDate IS NULL THEN RequestDate
				                    ELSE OrderReceiptDate
				                END AS DATE
				            ) AS [Date],
				            Quantity, Vendor,SimulationId,'Projected' as Firm_Projected
				        FROM SimulationSupplyOrders
				        WHERE
				            CASE
				                WHEN OrderReceiptDate IS NULL THEN RequestDate
				                ELSE OrderReceiptDate
				            END > cast(GETDATE() as date)
				    ) AS CombinedSupply
				    GROUP BY Id, [Date], OrderNumber,StartDate,[OrderType],Vendor,SimulationId,Firm_Projected
				)
				 SELECT
				        t1.Id,t1.StartDate,t1.SimulationId,t1.OrderType,
				       t1.[Date] as PromiseDate,
				        CAST(
				            ISNULL(t2.PromiseDate, t1.[Date]) AS DATE
				        ) AS [SchedulingDate],        CAST(
				            ISNULL(t2.PlannedReleaseDate, t1.[StartDate]) AS DATE
				        ) AS PlannedReleaseDate,
				        SUM(t1.SupplyQty) AS SupplyQty
				    FROM SupplyByDay t1
				    left JOIN report.SchedulingOrders t2
				        ON t1.OrderNumber = t2.OrderNumber
				        AND t1.Id = t2.PartId
				    GROUP BY t1.Id,t1.OrderType,t1.SimulationId, CAST(ISNULL(t2.PromiseDate, t1.[Date]) AS DATE),t1.[Date],t1.StartDate,t2.PlannedReleaseDate;
				"]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"PromiseDate", type date}, {"StartDate", type date}, {"SchedulingDate", type date}, {"PlannedReleaseDate", type date}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

