table UDF
	isHidden
	lineageTag: c38cb99e-7de3-47e6-8ab3-8a29d3f00817

	column UserDefined1
		dataType: string
		isHidden
		lineageTag: d197f6db-f8de-450c-b7bb-cf24981850ee
		summarizeBy: none
		sourceColumn: UserDefined1

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UserDefined2
		dataType: string
		isHidden
		lineageTag: dfbc6079-1322-47b1-9708-ae50c05a79e1
		summarizeBy: none
		sourceColumn: UserDefined2

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UserDefined3
		dataType: string
		isHidden
		lineageTag: 1bad06c3-dc93-41af-80ec-a5985a55e12f
		summarizeBy: none
		sourceColumn: UserDefined3

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UserDefined4
		dataType: string
		isHidden
		lineageTag: 5a0f27be-0419-4d93-815a-176ded8354e7
		summarizeBy: none
		sourceColumn: UserDefined4

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UserDefined5
		dataType: string
		isHidden
		lineageTag: e76a650d-8d42-480f-814c-e3aadbac9692
		summarizeBy: none
		sourceColumn: UserDefined5

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UserDefined6
		dataType: string
		isHidden
		lineageTag: 45d96fba-d3f2-4835-af57-8d417c4567f2
		summarizeBy: none
		sourceColumn: UserDefined6

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UserDefined7
		dataType: string
		isHidden
		lineageTag: 88bc9b28-db5b-4d23-b941-21b370ae0bff
		summarizeBy: none
		sourceColumn: UserDefined7

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UserDefined8
		dataType: string
		isHidden
		lineageTag: f1a3e156-d05b-4a9a-bf4a-23a86587a101
		summarizeBy: none
		sourceColumn: UserDefined8

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UserDefined9
		dataType: string
		isHidden
		lineageTag: 70505502-2b44-4173-8c90-ee780d12a2a0
		summarizeBy: none
		sourceColumn: UserDefined9

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UserDefined10
		dataType: string
		isHidden
		lineageTag: b29d38b1-daae-4142-a9d0-2249a7d6668f
		summarizeBy: none
		sourceColumn: UserDefined10

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UserDefined11
		dataType: string
		isHidden
		lineageTag: 28001d5e-3490-4dff-b5e7-f119dc3b60cb
		summarizeBy: none
		sourceColumn: UserDefined11

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UserDefined12
		dataType: string
		isHidden
		lineageTag: 5e1d32cf-85f1-4ce9-98c2-6eae88cdb609
		summarizeBy: none
		sourceColumn: UserDefined12

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UserDefined13
		dataType: string
		isHidden
		lineageTag: edfb9b92-903a-42e6-860d-a4a8f2cf61e9
		summarizeBy: none
		sourceColumn: UserDefined13

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UserDefined14
		dataType: string
		isHidden
		lineageTag: 06d866e6-7bff-42aa-8954-518f2045c3c3
		summarizeBy: none
		sourceColumn: UserDefined14

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UserDefined15
		dataType: string
		isHidden
		lineageTag: 412425df-02dc-412e-84bd-0877d18073f2
		summarizeBy: none
		sourceColumn: UserDefined15

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UserDefined16
		dataType: string
		isHidden
		lineageTag: 357a6cd8-5e5e-41f2-a426-42fcc03f2ae4
		summarizeBy: none
		sourceColumn: UserDefined16

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition UDF-cbda0a86-0629-4d9e-b039-e36e2e638021 = m
		mode: import
		source =
				let
				    Source = Sql.Database(Server, Database, [Query="select Value from KeyValueItems where id='Settings.Global.Engine'"]),
				    #"TransformColumns"=Table.TransformColumns(Source,{{"Value", Json.Document}}),
				    #"Value développé" = Table.ExpandRecordColumn(TransformColumns, "Value", {"UDF1", "UDF2", "UDF3", "UDF4", "UDF5", "UDF6", "UDF7", "UDF8", "UDF9", "UDF10", "UDF11", "UDF12", "UDF13", "UDF14", "UDF15", "UDF16"}, {"UDF1", "UDF2", "UDF3", "UDF4", "UDF5", "UDF6", "UDF7", "UDF8", "UDF9", "UDF10", "UDF11", "UDF12", "UDF13", "UDF14", "UDF15", "UDF16"}),
				    #"Colonnes renommées1" = Table.RenameColumns(#"Value développé",{{"UDF1", "UserDefined1"}, {"UDF2", "UserDefined2"}, {"UDF3", "UserDefined3"}, {"UDF4", "UserDefined4"}, {"UDF5", "UserDefined5"}, {"UDF6", "UserDefined6"}, {"UDF7", "UserDefined7"}, {"UDF8", "UserDefined8"}, {"UDF9", "UserDefined9"}, {"UDF10", "UserDefined10"}, {"UDF11", "UserDefined11"}, {"UDF12", "UserDefined12"}, {"UDF13", "UserDefined13"}, {"UDF14", "UserDefined14"}, {"UDF15", "UserDefined15"}, {"UDF16", "UserDefined16"}}),
				    #"Type modifié" = Table.TransformColumnTypes(#"Colonnes renommées1",{{"UserDefined2", type text}, {"UserDefined1", type text}, {"UserDefined3", type text}, {"UserDefined4", type text}, {"UserDefined5", type text}, {"UserDefined6", type text}, {"UserDefined7", type text}, {"UserDefined8", type text}, {"UserDefined9", type text}, {"UserDefined10", type text}, {"UserDefined11", type text}, {"UserDefined12", type text}, {"UserDefined13", type text}, {"UserDefined14", type text}, {"UserDefined15", type text}, {"UserDefined16", type text}})
				in
				    #"Type modifié"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

